// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         name: "name",
 *         algorithm: Chronocast.Algorithm.arima({
 *             orderP: 1,
 *             orderD: 1,
 *             orderQ: 1
 *         }),
 *         datasetId: "dataset_id",
 *         targetColumn: "target_column",
 *         featureColumns: ["feature_columns"]
 *     }
 */
export interface ModelCreate {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    name: string;
    algorithm: Chronocast.Algorithm;
    datasetId: string;
    targetColumn: string;
    featureColumns: string[];
    hyperparameters?: Chronocast.Hyperparameters;
}
