// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key"
 *     }
 */
export interface TrainModelRequest {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    hyperparameters?: Chronocast.Hyperparameters;
}
