/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsCreateAlert } from "../funcs/alerts-create-alert.js";
import { alertsDeleteAlert } from "../funcs/alerts-delete-alert.js";
import { alertsGetAlert } from "../funcs/alerts-get-alert.js";
import { alertsListAlertHistory } from "../funcs/alerts-list-alert-history.js";
import { alertsListAlerts } from "../funcs/alerts-list-alerts.js";
import { alertsUpdateAlert } from "../funcs/alerts-update-alert.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Alerts extends ClientSDK {
  /**
   * List alerts in a project
   */
  async listAlerts(
    request: operations.ListAlertsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAlertsResponse> {
    return unwrapAsync(alertsListAlerts(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an alert
   */
  async createAlert(
    request: operations.CreateAlertRequest,
    options?: RequestOptions,
  ): Promise<models.Alert> {
    return unwrapAsync(alertsCreateAlert(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an alert
   */
  async getAlert(
    request: operations.GetAlertRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAlertResponse> {
    return unwrapAsync(alertsGetAlert(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an alert
   */
  async updateAlert(
    request: operations.UpdateAlertRequest,
    options?: RequestOptions,
  ): Promise<models.Alert> {
    return unwrapAsync(alertsUpdateAlert(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an alert
   */
  async deleteAlert(
    request: operations.DeleteAlertRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(alertsDeleteAlert(
      this,
      request,
      options,
    ));
  }

  /**
   * List alert event history (offset-paginated)
   */
  async listAlertHistory(
    request: operations.ListAlertHistoryRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAlertHistoryResponse> {
    return unwrapAsync(alertsListAlertHistory(
      this,
      request,
      options,
    ));
  }
}
