/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { membersInviteMember } from "../funcs/members-invite-member.js";
import { membersListMembers } from "../funcs/members-list-members.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Members extends ClientSDK {
  /**
   * List organization members
   */
  async listMembers(
    request: operations.ListMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.ListMembersResponse> {
    return unwrapAsync(membersListMembers(
      this,
      request,
      options,
    ));
  }

  /**
   * Invite a member to the organization
   */
  async inviteMember(
    request: operations.InviteMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.InviteMemberResponse> {
    return unwrapAsync(membersInviteMember(
      this,
      request,
      options,
    ));
  }
}
