/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsCreateModel } from "../funcs/models-create-model.js";
import { modelsDeleteModel } from "../funcs/models-delete-model.js";
import { modelsGetModel } from "../funcs/models-get-model.js";
import { modelsListModels } from "../funcs/models-list-models.js";
import { modelsTrainModel } from "../funcs/models-train-model.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List forecast models
   */
  async listModels(
    request: operations.ListModelsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListModelsResponse> {
    return unwrapAsync(modelsListModels(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a forecast model
   */
  async createModel(
    request: operations.CreateModelRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateModelResponse> {
    return unwrapAsync(modelsCreateModel(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a forecast model
   */
  async getModel(
    request: operations.GetModelRequest,
    options?: RequestOptions,
  ): Promise<operations.GetModelResponse> {
    return unwrapAsync(modelsGetModel(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a forecast model
   */
  async deleteModel(
    request: operations.DeleteModelRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(modelsDeleteModel(
      this,
      request,
      options,
    ));
  }

  /**
   * Start model training (async, returns operation to poll)
   */
  async trainModel(
    request: operations.TrainModelRequest,
    options?: RequestOptions,
  ): Promise<operations.TrainModelResponse> {
    return unwrapAsync(modelsTrainModel(
      this,
      request,
      options,
    ));
  }
}
