/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operationsCancelOperation } from "../funcs/operations-cancel-operation.js";
import { operationsGetOperation } from "../funcs/operations-get-operation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Operations extends ClientSDK {
  /**
   * Poll an async operation
   */
  async getOperation(
    request: operations.GetOperationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOperationResponse> {
    return unwrapAsync(operationsGetOperation(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a running async operation
   */
  async cancelOperation(
    request: operations.CancelOperationRequest,
    options?: RequestOptions,
  ): Promise<operations.CancelOperationResponse> {
    return unwrapAsync(operationsCancelOperation(
      this,
      request,
      options,
    ));
  }
}
