/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsCreateOrganization } from "../funcs/organizations-create-organization.js";
import { organizationsDeleteOrganization } from "../funcs/organizations-delete-organization.js";
import { organizationsGetOrganization } from "../funcs/organizations-get-organization.js";
import { organizationsListOrganizations } from "../funcs/organizations-list-organizations.js";
import { organizationsUpdateOrganization } from "../funcs/organizations-update-organization.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organizations extends ClientSDK {
  /**
   * List organizations
   */
  async listOrganizations(
    request?: operations.ListOrganizationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListOrganizationsResponse> {
    return unwrapAsync(organizationsListOrganizations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an organization
   */
  async createOrganization(
    request: operations.CreateOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOrganizationResponse> {
    return unwrapAsync(organizationsCreateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an organization
   */
  async getOrganization(
    request: operations.GetOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationResponse> {
    return unwrapAsync(organizationsGetOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an organization
   */
  async updateOrganization(
    request: operations.UpdateOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateOrganizationResponse> {
    return unwrapAsync(organizationsUpdateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an organization
   */
  async deleteOrganization(
    request: operations.DeleteOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteOrganizationResponse | undefined> {
    return unwrapAsync(organizationsDeleteOrganization(
      this,
      request,
      options,
    ));
  }
}
