/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCreateProject } from "../funcs/projects-create-project.js";
import { projectsDeleteProject } from "../funcs/projects-delete-project.js";
import { projectsGetProject } from "../funcs/projects-get-project.js";
import { projectsListProjects } from "../funcs/projects-list-projects.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List projects in an organization
   */
  async listProjects(
    request: operations.ListProjectsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListProjectsResponse> {
    return unwrapAsync(projectsListProjects(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a project
   */
  async createProject(
    request: operations.CreateProjectRequest,
    options?: RequestOptions,
  ): Promise<models.Project> {
    return unwrapAsync(projectsCreateProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a project
   */
  async getProject(
    request: operations.GetProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectResponse> {
    return unwrapAsync(projectsGetProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a project
   */
  async deleteProject(
    request: operations.DeleteProjectRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(projectsDeleteProject(
      this,
      request,
      options,
    ));
  }
}
