/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Alerts } from "./alerts.js";
import { Datasets } from "./datasets.js";
import { Members } from "./members.js";
import { Models } from "./models.js";
import { Operations } from "./operations.js";
import { Organizations } from "./organizations.js";
import { Predictions } from "./predictions.js";
import { Projects } from "./projects.js";
import { Webhooks } from "./webhooks.js";

export class SDK extends ClientSDK {
  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _members?: Members;
  get members(): Members {
    return (this._members ??= new Members(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _datasets?: Datasets;
  get datasets(): Datasets {
    return (this._datasets ??= new Datasets(this._options));
  }

  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _predictions?: Predictions;
  get predictions(): Predictions {
    return (this._predictions ??= new Predictions(this._options));
  }

  private _alerts?: Alerts;
  get alerts(): Alerts {
    return (this._alerts ??= new Alerts(this._options));
  }

  private _operations?: Operations;
  get operations(): Operations {
    return (this._operations ??= new Operations(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }
}
