/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreateWebhook } from "../funcs/webhooks-create-webhook.js";
import { webhooksDeleteWebhook } from "../funcs/webhooks-delete-webhook.js";
import { webhooksGetWebhook } from "../funcs/webhooks-get-webhook.js";
import { webhooksListWebhookDeliveries } from "../funcs/webhooks-list-webhook-deliveries.js";
import { webhooksListWebhooks } from "../funcs/webhooks-list-webhooks.js";
import { webhooksVerifyWebhookSignature } from "../funcs/webhooks-verify-webhook-signature.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List webhook endpoints
   */
  async listWebhooks(
    security: operations.ListWebhooksSecurity,
    request?: operations.ListWebhooksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListWebhooksResponse> {
    return unwrapAsync(webhooksListWebhooks(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a webhook endpoint
   */
  async createWebhook(
    security: operations.CreateWebhookSecurity,
    request: operations.CreateWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.WebhookEndpoint> {
    return unwrapAsync(webhooksCreateWebhook(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Retrieve a webhook endpoint
   */
  async getWebhook(
    security: operations.GetWebhookSecurity,
    request: operations.GetWebhookRequest,
    options?: RequestOptions,
  ): Promise<operations.GetWebhookResponse> {
    return unwrapAsync(webhooksGetWebhook(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a webhook endpoint
   */
  async deleteWebhook(
    security: operations.DeleteWebhookSecurity,
    request: operations.DeleteWebhookRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksDeleteWebhook(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List delivery attempts for a webhook
   */
  async listWebhookDeliveries(
    security: operations.ListWebhookDeliveriesSecurity,
    request: operations.ListWebhookDeliveriesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListWebhookDeliveriesResponse> {
    return unwrapAsync(webhooksListWebhookDeliveries(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Verify a webhook payload signature
   */
  async verifyWebhookSignature(
    request: operations.VerifyWebhookSignatureRequest,
    options?: RequestOptions,
  ): Promise<operations.VerifyWebhookSignatureResponse> {
    return unwrapAsync(webhooksVerifyWebhookSignature(
      this,
      request,
      options,
    ));
  }
}
