// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { OrganizationCreatePlan } from "../../types/OrganizationCreatePlan.js";

export const OrganizationCreate: core.serialization.Schema<
    serializers.OrganizationCreate.Raw,
    Omit<Chronocast.OrganizationCreate, "idempotencyKey">
> = core.serialization.object({
    name: core.serialization.string(),
    slug: core.serialization.string(),
    plan: OrganizationCreatePlan.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace OrganizationCreate {
    export interface Raw {
        name: string;
        slug: string;
        plan?: OrganizationCreatePlan.Raw | null;
        metadata?: Record<string, string> | null;
    }
}
