// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { UpdateOrganizationRequestPlan } from "../../types/UpdateOrganizationRequestPlan.js";

export const UpdateOrganizationRequest: core.serialization.Schema<
    serializers.UpdateOrganizationRequest.Raw,
    Chronocast.UpdateOrganizationRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    plan: UpdateOrganizationRequestPlan.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
});

export declare namespace UpdateOrganizationRequest {
    export interface Raw {
        name?: string | null;
        plan?: UpdateOrganizationRequestPlan.Raw | null;
        metadata?: Record<string, string | null | undefined> | null;
    }
}
