// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../index.js";

export interface ListOrganizationsResponse {
    data?: Chronocast.Organization[];
    hasMore: boolean;
    nextCursor?: string;
}
