// This file was auto-generated by Fern from our API Definition.

export const OrganizationCreatePlan = {
    Free: "free",
    Pro: "pro",
    Enterprise: "enterprise",
    _visit: <R>(value: OrganizationCreatePlan, visitor: OrganizationCreatePlan.Visitor<R>) => {
        switch (value) {
            case OrganizationCreatePlan.Free:
                return visitor.free();
            case OrganizationCreatePlan.Pro:
                return visitor.pro();
            case OrganizationCreatePlan.Enterprise:
                return visitor.enterprise();
            default:
                return visitor._other();
        }
    },
} as const;
export type OrganizationCreatePlan = Omit<typeof OrganizationCreatePlan, "_visit">[keyof Omit<
    typeof OrganizationCreatePlan,
    "_visit"
>];

export namespace OrganizationCreatePlan {
    export interface Visitor<R> {
        free: () => R;
        pro: () => R;
        enterprise: () => R;
        _other: () => R;
    }
}
