// This file was auto-generated by Fern from our API Definition.

export const UpdateOrganizationRequestPlan = {
    Free: "free",
    Pro: "pro",
    Enterprise: "enterprise",
    _visit: <R>(value: UpdateOrganizationRequestPlan, visitor: UpdateOrganizationRequestPlan.Visitor<R>) => {
        switch (value) {
            case UpdateOrganizationRequestPlan.Free:
                return visitor.free();
            case UpdateOrganizationRequestPlan.Pro:
                return visitor.pro();
            case UpdateOrganizationRequestPlan.Enterprise:
                return visitor.enterprise();
            default:
                return visitor._other();
        }
    },
} as const;
export type UpdateOrganizationRequestPlan = Omit<typeof UpdateOrganizationRequestPlan, "_visit">[keyof Omit<
    typeof UpdateOrganizationRequestPlan,
    "_visit"
>];

export namespace UpdateOrganizationRequestPlan {
    export interface Visitor<R> {
        free: () => R;
        pro: () => R;
        enterprise: () => R;
        _other: () => R;
    }
}
