// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListModelsRequestStatus: core.serialization.Schema<
    serializers.ListModelsRequestStatus.Raw,
    Chronocast.ListModelsRequestStatus
> = core.serialization.enum_(["draft", "training", "trained", "failed", "archived"]);

export declare namespace ListModelsRequestStatus {
    export type Raw = "draft" | "training" | "trained" | "failed" | "archived";
}
