// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ForecastModel } from "../../../types/ForecastModel.js";

export const ListModelsResponse: core.serialization.ObjectSchema<
    serializers.ListModelsResponse.Raw,
    Chronocast.ListModelsResponse
> = core.serialization.object({
    data: core.serialization.list(ForecastModel).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListModelsResponse {
    export interface Raw {
        data?: ForecastModel.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
