// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const ProjectCreate: core.serialization.Schema<
    serializers.ProjectCreate.Raw,
    Omit<Chronocast.ProjectCreate, "idempotencyKey">
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace ProjectCreate {
    export interface Raw {
        name: string;
        description?: string | null;
    }
}
