// This file was auto-generated by Fern from our API Definition.

export const ListMembersRequestRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
    Viewer: "viewer",
    _visit: <R>(value: ListMembersRequestRole, visitor: ListMembersRequestRole.Visitor<R>) => {
        switch (value) {
            case ListMembersRequestRole.Owner:
                return visitor.owner();
            case ListMembersRequestRole.Admin:
                return visitor.admin();
            case ListMembersRequestRole.Member:
                return visitor.member();
            case ListMembersRequestRole.Viewer:
                return visitor.viewer();
            default:
                return visitor._other();
        }
    },
} as const;
export type ListMembersRequestRole = Omit<typeof ListMembersRequestRole, "_visit">[keyof Omit<
    typeof ListMembersRequestRole,
    "_visit"
>];

export namespace ListMembersRequestRole {
    export interface Visitor<R> {
        owner: () => R;
        admin: () => R;
        member: () => R;
        viewer: () => R;
        _other: () => R;
    }
}
