// This file was auto-generated by Fern from our API Definition.

export const MemberInviteRole = {
    Admin: "admin",
    Member: "member",
    Viewer: "viewer",
    _visit: <R>(value: MemberInviteRole, visitor: MemberInviteRole.Visitor<R>) => {
        switch (value) {
            case MemberInviteRole.Admin:
                return visitor.admin();
            case MemberInviteRole.Member:
                return visitor.member();
            case MemberInviteRole.Viewer:
                return visitor.viewer();
            default:
                return visitor._other();
        }
    },
} as const;
export type MemberInviteRole = Omit<typeof MemberInviteRole, "_visit">[keyof Omit<typeof MemberInviteRole, "_visit">];

export namespace MemberInviteRole {
    export interface Visitor<R> {
        admin: () => R;
        member: () => R;
        viewer: () => R;
        _other: () => R;
    }
}
