// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cursor: "cursor",
 *         limit: 1
 *     }
 */
export interface ListWebhooksRequest {
    /** Opaque cursor for cursor-based pagination. */
    cursor?: string;
    limit?: number;
}
