// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         payload: "payload",
 *         signature: "signature",
 *         timestamp: new Date("2024-01-15T09:30:00.000Z")
 *     }
 */
export interface VerifyWebhookSignatureRequest {
    /** Raw JSON payload string */
    payload: string;
    /** The X-Chronocast-Signature header value */
    signature: string;
    /** The X-Chronocast-Timestamp header value */
    timestamp: Date;
}
