// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         url: "url",
 *         events: ["model.training.started"]
 *     }
 */
export interface WebhookEndpointCreate {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    url: string;
    events: Chronocast.WebhookEndpointCreateEventsItem[];
}
