// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface Alert {
    id: string;
    projectId: string;
    name: string;
    modelId: string;
    condition: Chronocast.AlertCondition;
    channels: Chronocast.NotificationChannel[];
    enabled: boolean;
    createdAt: Date;
}
