// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type AlertCondition =
    | Chronocast.AlertCondition.Threshold
    | Chronocast.AlertCondition.Anomaly
    | Chronocast.AlertCondition.Trend;

export namespace AlertCondition {
    export interface Threshold extends Chronocast.ThresholdCondition, _Utils {
        type: "threshold";
    }

    export interface Anomaly extends Chronocast.AnomalyCondition, _Utils {
        type: "anomaly";
    }

    export interface Trend extends Chronocast.TrendCondition, _Utils {
        type: "trend";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.AlertCondition._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        threshold: (value: Chronocast.ThresholdCondition) => _Result;
        anomaly: (value: Chronocast.AnomalyCondition) => _Result;
        trend: (value: Chronocast.TrendCondition) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const AlertCondition = {
    threshold: (value: Chronocast.ThresholdCondition): Chronocast.AlertCondition.Threshold => {
        return {
            ...value,
            type: "threshold",
            _visit: function <_Result>(
                this: Chronocast.AlertCondition.Threshold,
                visitor: Chronocast.AlertCondition._Visitor<_Result>,
            ) {
                return Chronocast.AlertCondition._visit(this, visitor);
            },
        };
    },

    anomaly: (value: Chronocast.AnomalyCondition): Chronocast.AlertCondition.Anomaly => {
        return {
            ...value,
            type: "anomaly",
            _visit: function <_Result>(
                this: Chronocast.AlertCondition.Anomaly,
                visitor: Chronocast.AlertCondition._Visitor<_Result>,
            ) {
                return Chronocast.AlertCondition._visit(this, visitor);
            },
        };
    },

    trend: (value: Chronocast.TrendCondition): Chronocast.AlertCondition.Trend => {
        return {
            ...value,
            type: "trend",
            _visit: function <_Result>(
                this: Chronocast.AlertCondition.Trend,
                visitor: Chronocast.AlertCondition._Visitor<_Result>,
            ) {
                return Chronocast.AlertCondition._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: Chronocast.AlertCondition,
        visitor: Chronocast.AlertCondition._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "threshold":
                return visitor.threshold(value);
            case "anomaly":
                return visitor.anomaly(value);
            case "trend":
                return visitor.trend(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
