// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface AlertEvent {
    id: string;
    alertId: string;
    triggeredAt: Date;
    conditionSnapshot: Chronocast.AlertCondition;
    observedValue: number;
    resolvedAt?: Date;
}
