// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type Algorithm = Chronocast.Algorithm.Arima | Chronocast.Algorithm.Neural | Chronocast.Algorithm.Ensemble;

export namespace Algorithm {
    export interface Arima extends Chronocast.ArimaAlgorithm, _Utils {
        type: "arima";
    }

    export interface Neural extends Chronocast.NeuralAlgorithm, _Utils {
        type: "neural";
    }

    export interface Ensemble extends Chronocast.EnsembleAlgorithm, _Utils {
        type: "ensemble";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.Algorithm._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        arima: (value: Chronocast.ArimaAlgorithm) => _Result;
        neural: (value: Chronocast.NeuralAlgorithm) => _Result;
        ensemble: (value: Chronocast.EnsembleAlgorithm) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Algorithm = {
    arima: (value: Chronocast.ArimaAlgorithm): Chronocast.Algorithm.Arima => {
        return {
            ...value,
            type: "arima",
            _visit: function <_Result>(
                this: Chronocast.Algorithm.Arima,
                visitor: Chronocast.Algorithm._Visitor<_Result>,
            ) {
                return Chronocast.Algorithm._visit(this, visitor);
            },
        };
    },

    neural: (value: Chronocast.NeuralAlgorithm): Chronocast.Algorithm.Neural => {
        return {
            ...value,
            type: "neural",
            _visit: function <_Result>(
                this: Chronocast.Algorithm.Neural,
                visitor: Chronocast.Algorithm._Visitor<_Result>,
            ) {
                return Chronocast.Algorithm._visit(this, visitor);
            },
        };
    },

    ensemble: (value: Chronocast.EnsembleAlgorithm): Chronocast.Algorithm.Ensemble => {
        return {
            ...value,
            type: "ensemble",
            _visit: function <_Result>(
                this: Chronocast.Algorithm.Ensemble,
                visitor: Chronocast.Algorithm._Visitor<_Result>,
            ) {
                return Chronocast.Algorithm._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: Chronocast.Algorithm, visitor: Chronocast.Algorithm._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "arima":
                return visitor.arima(value);
            case "neural":
                return visitor.neural(value);
            case "ensemble":
                return visitor.ensemble(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
