// This file was auto-generated by Fern from our API Definition.

export interface AnomalyCondition {
    /** 0 = least sensitive, 1 = most sensitive */
    sensitivity: number;
    minDeviationPct?: number;
}
