// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface ApiError {
    type: Chronocast.ApiErrorType;
    message: string;
    requestId: string;
    details?: Chronocast.FieldError[];
}
