// This file was auto-generated by Fern from our API Definition.

export const ApiErrorType = {
    InvalidRequest: "invalid_request",
    AuthenticationError: "authentication_error",
    PermissionDenied: "permission_denied",
    NotFound: "not_found",
    RateLimit: "rate_limit",
    Conflict: "conflict",
    InternalError: "internal_error",
    _visit: <R>(value: ApiErrorType, visitor: ApiErrorType.Visitor<R>) => {
        switch (value) {
            case ApiErrorType.InvalidRequest:
                return visitor.invalidRequest();
            case ApiErrorType.AuthenticationError:
                return visitor.authenticationError();
            case ApiErrorType.PermissionDenied:
                return visitor.permissionDenied();
            case ApiErrorType.NotFound:
                return visitor.notFound();
            case ApiErrorType.RateLimit:
                return visitor.rateLimit();
            case ApiErrorType.Conflict:
                return visitor.conflict();
            case ApiErrorType.InternalError:
                return visitor.internalError();
            default:
                return visitor._other();
        }
    },
} as const;
export type ApiErrorType = Omit<typeof ApiErrorType, "_visit">[keyof Omit<typeof ApiErrorType, "_visit">];

export namespace ApiErrorType {
    export interface Visitor<R> {
        invalidRequest: () => R;
        authenticationError: () => R;
        permissionDenied: () => R;
        notFound: () => R;
        rateLimit: () => R;
        conflict: () => R;
        internalError: () => R;
        _other: () => R;
    }
}
