// This file was auto-generated by Fern from our API Definition.

export const AsyncOperationStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
    _visit: <R>(value: AsyncOperationStatus, visitor: AsyncOperationStatus.Visitor<R>) => {
        switch (value) {
            case AsyncOperationStatus.Pending:
                return visitor.pending();
            case AsyncOperationStatus.Running:
                return visitor.running();
            case AsyncOperationStatus.Succeeded:
                return visitor.succeeded();
            case AsyncOperationStatus.Failed:
                return visitor.failed();
            case AsyncOperationStatus.Cancelled:
                return visitor.cancelled();
            default:
                return visitor._other();
        }
    },
} as const;
export type AsyncOperationStatus = Omit<typeof AsyncOperationStatus, "_visit">[keyof Omit<
    typeof AsyncOperationStatus,
    "_visit"
>];

export namespace AsyncOperationStatus {
    export interface Visitor<R> {
        pending: () => R;
        running: () => R;
        succeeded: () => R;
        failed: () => R;
        cancelled: () => R;
        _other: () => R;
    }
}
