// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface AsyncOperation {
    id: string;
    status: Chronocast.AsyncOperationStatus;
    createdAt: Date;
    updatedAt: Date;
    resultUrl?: string;
    error?: Chronocast.OperationError;
    progressPct?: number;
}
