// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type BatchPredictionResponseResultsItem =
    | Chronocast.BatchPredictionResponseResultsItem.Result
    | Chronocast.BatchPredictionResponseResultsItem.Error_;

export namespace BatchPredictionResponseResultsItem {
    export interface Result extends Chronocast.PredictionResult, _Utils {
        resultType: "result";
    }

    export interface Error_ extends Chronocast.BatchItemError, _Utils {
        resultType: "error";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.BatchPredictionResponseResultsItem._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        result: (value: Chronocast.PredictionResult) => _Result;
        error: (value: Chronocast.BatchItemError) => _Result;
        _other: (value: { resultType: string }) => _Result;
    }
}

export const BatchPredictionResponseResultsItem = {
    result: (value: Chronocast.PredictionResult): Chronocast.BatchPredictionResponseResultsItem.Result => {
        return {
            ...value,
            resultType: "result",
            _visit: function <_Result>(
                this: Chronocast.BatchPredictionResponseResultsItem.Result,
                visitor: Chronocast.BatchPredictionResponseResultsItem._Visitor<_Result>,
            ) {
                return Chronocast.BatchPredictionResponseResultsItem._visit(this, visitor);
            },
        };
    },

    error: (value: Chronocast.BatchItemError): Chronocast.BatchPredictionResponseResultsItem.Error_ => {
        return {
            ...value,
            resultType: "error",
            _visit: function <_Result>(
                this: Chronocast.BatchPredictionResponseResultsItem.Error_,
                visitor: Chronocast.BatchPredictionResponseResultsItem._Visitor<_Result>,
            ) {
                return Chronocast.BatchPredictionResponseResultsItem._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: Chronocast.BatchPredictionResponseResultsItem,
        visitor: Chronocast.BatchPredictionResponseResultsItem._Visitor<_Result>,
    ): _Result => {
        switch (value.resultType) {
            case "result":
                return visitor.result(value);
            case "error":
                return visitor.error(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
