// This file was auto-generated by Fern from our API Definition.

export const ColumnSchemaDtype = {
    Float64: "float64",
    Int64: "int64",
    String: "string",
    Datetime: "datetime",
    Boolean: "boolean",
    _visit: <R>(value: ColumnSchemaDtype, visitor: ColumnSchemaDtype.Visitor<R>) => {
        switch (value) {
            case ColumnSchemaDtype.Float64:
                return visitor.float64();
            case ColumnSchemaDtype.Int64:
                return visitor.int64();
            case ColumnSchemaDtype.String:
                return visitor.string();
            case ColumnSchemaDtype.Datetime:
                return visitor.datetime();
            case ColumnSchemaDtype.Boolean:
                return visitor.boolean();
            default:
                return visitor._other();
        }
    },
} as const;
export type ColumnSchemaDtype = Omit<typeof ColumnSchemaDtype, "_visit">[keyof Omit<
    typeof ColumnSchemaDtype,
    "_visit"
>];

export namespace ColumnSchemaDtype {
    export interface Visitor<R> {
        float64: () => R;
        int64: () => R;
        string: () => R;
        datetime: () => R;
        boolean: () => R;
        _other: () => R;
    }
}
