// This file was auto-generated by Fern from our API Definition.

export const DatasetFormat = {
    Csv: "csv",
    Parquet: "parquet",
    Json: "json",
    _visit: <R>(value: DatasetFormat, visitor: DatasetFormat.Visitor<R>) => {
        switch (value) {
            case DatasetFormat.Csv:
                return visitor.csv();
            case DatasetFormat.Parquet:
                return visitor.parquet();
            case DatasetFormat.Json:
                return visitor.json();
            default:
                return visitor._other();
        }
    },
} as const;
export type DatasetFormat = Omit<typeof DatasetFormat, "_visit">[keyof Omit<typeof DatasetFormat, "_visit">];

export namespace DatasetFormat {
    export interface Visitor<R> {
        csv: () => R;
        parquet: () => R;
        json: () => R;
        _other: () => R;
    }
}
