// This file was auto-generated by Fern from our API Definition.

export const DatasetStatus = {
    Uploading: "uploading",
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
    _visit: <R>(value: DatasetStatus, visitor: DatasetStatus.Visitor<R>) => {
        switch (value) {
            case DatasetStatus.Uploading:
                return visitor.uploading();
            case DatasetStatus.Processing:
                return visitor.processing();
            case DatasetStatus.Ready:
                return visitor.ready();
            case DatasetStatus.Failed:
                return visitor.failed();
            default:
                return visitor._other();
        }
    },
} as const;
export type DatasetStatus = Omit<typeof DatasetStatus, "_visit">[keyof Omit<typeof DatasetStatus, "_visit">];

export namespace DatasetStatus {
    export interface Visitor<R> {
        uploading: () => R;
        processing: () => R;
        ready: () => R;
        failed: () => R;
        _other: () => R;
    }
}
