// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type DataSource =
    | Chronocast.DataSource.FileUpload
    | Chronocast.DataSource.WebhookIngest
    | Chronocast.DataSource.ApiPull;

export namespace DataSource {
    export interface FileUpload extends Chronocast.FileUploadSource, _Utils {
        type: "file_upload";
    }

    export interface WebhookIngest extends Chronocast.WebhookIngestSource, _Utils {
        type: "webhook_ingest";
    }

    export interface ApiPull extends Chronocast.ApiPullSource, _Utils {
        type: "api_pull";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.DataSource._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        fileUpload: (value: Chronocast.FileUploadSource) => _Result;
        webhookIngest: (value: Chronocast.WebhookIngestSource) => _Result;
        apiPull: (value: Chronocast.ApiPullSource) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const DataSource = {
    fileUpload: (value: Chronocast.FileUploadSource): Chronocast.DataSource.FileUpload => {
        return {
            ...value,
            type: "file_upload",
            _visit: function <_Result>(
                this: Chronocast.DataSource.FileUpload,
                visitor: Chronocast.DataSource._Visitor<_Result>,
            ) {
                return Chronocast.DataSource._visit(this, visitor);
            },
        };
    },

    webhookIngest: (value: Chronocast.WebhookIngestSource): Chronocast.DataSource.WebhookIngest => {
        return {
            ...value,
            type: "webhook_ingest",
            _visit: function <_Result>(
                this: Chronocast.DataSource.WebhookIngest,
                visitor: Chronocast.DataSource._Visitor<_Result>,
            ) {
                return Chronocast.DataSource._visit(this, visitor);
            },
        };
    },

    apiPull: (value: Chronocast.ApiPullSource): Chronocast.DataSource.ApiPull => {
        return {
            ...value,
            type: "api_pull",
            _visit: function <_Result>(
                this: Chronocast.DataSource.ApiPull,
                visitor: Chronocast.DataSource._Visitor<_Result>,
            ) {
                return Chronocast.DataSource._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: Chronocast.DataSource, visitor: Chronocast.DataSource._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "file_upload":
                return visitor.fileUpload(value);
            case "webhook_ingest":
                return visitor.webhookIngest(value);
            case "api_pull":
                return visitor.apiPull(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
