// This file was auto-generated by Fern from our API Definition.

export const EnsembleAlgorithmCombinationMethod = {
    Average: "average",
    Weighted: "weighted",
    Stacking: "stacking",
    _visit: <R>(value: EnsembleAlgorithmCombinationMethod, visitor: EnsembleAlgorithmCombinationMethod.Visitor<R>) => {
        switch (value) {
            case EnsembleAlgorithmCombinationMethod.Average:
                return visitor.average();
            case EnsembleAlgorithmCombinationMethod.Weighted:
                return visitor.weighted();
            case EnsembleAlgorithmCombinationMethod.Stacking:
                return visitor.stacking();
            default:
                return visitor._other();
        }
    },
} as const;
export type EnsembleAlgorithmCombinationMethod = Omit<typeof EnsembleAlgorithmCombinationMethod, "_visit">[keyof Omit<
    typeof EnsembleAlgorithmCombinationMethod,
    "_visit"
>];

export namespace EnsembleAlgorithmCombinationMethod {
    export interface Visitor<R> {
        average: () => R;
        weighted: () => R;
        stacking: () => R;
        _other: () => R;
    }
}
