// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface FieldError {
    field: string;
    message: string;
    code: Chronocast.FieldErrorCode;
}
