// This file was auto-generated by Fern from our API Definition.

export const FieldErrorCode = {
    Required: "required",
    InvalidFormat: "invalid_format",
    OutOfRange: "out_of_range",
    TooLong: "too_long",
    TooShort: "too_short",
    UniqueViolation: "unique_violation",
    _visit: <R>(value: FieldErrorCode, visitor: FieldErrorCode.Visitor<R>) => {
        switch (value) {
            case FieldErrorCode.Required:
                return visitor.required();
            case FieldErrorCode.InvalidFormat:
                return visitor.invalidFormat();
            case FieldErrorCode.OutOfRange:
                return visitor.outOfRange();
            case FieldErrorCode.TooLong:
                return visitor.tooLong();
            case FieldErrorCode.TooShort:
                return visitor.tooShort();
            case FieldErrorCode.UniqueViolation:
                return visitor.uniqueViolation();
            default:
                return visitor._other();
        }
    },
} as const;
export type FieldErrorCode = Omit<typeof FieldErrorCode, "_visit">[keyof Omit<typeof FieldErrorCode, "_visit">];

export namespace FieldErrorCode {
    export interface Visitor<R> {
        required: () => R;
        invalidFormat: () => R;
        outOfRange: () => R;
        tooLong: () => R;
        tooShort: () => R;
        uniqueViolation: () => R;
        _other: () => R;
    }
}
