// This file was auto-generated by Fern from our API Definition.

export const ForecastModelStatus = {
    Draft: "draft",
    Training: "training",
    Trained: "trained",
    Failed: "failed",
    Archived: "archived",
    _visit: <R>(value: ForecastModelStatus, visitor: ForecastModelStatus.Visitor<R>) => {
        switch (value) {
            case ForecastModelStatus.Draft:
                return visitor.draft();
            case ForecastModelStatus.Training:
                return visitor.training();
            case ForecastModelStatus.Trained:
                return visitor.trained();
            case ForecastModelStatus.Failed:
                return visitor.failed();
            case ForecastModelStatus.Archived:
                return visitor.archived();
            default:
                return visitor._other();
        }
    },
} as const;
export type ForecastModelStatus = Omit<typeof ForecastModelStatus, "_visit">[keyof Omit<
    typeof ForecastModelStatus,
    "_visit"
>];

export namespace ForecastModelStatus {
    export interface Visitor<R> {
        draft: () => R;
        training: () => R;
        trained: () => R;
        failed: () => R;
        archived: () => R;
        _other: () => R;
    }
}
