// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface ForecastPoint {
    timestamp: Date;
    value: number;
    confidenceIntervals?: Chronocast.ConfidenceInterval[];
}
