// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface ForecastModel {
    id: string;
    projectId: string;
    name: string;
    algorithm: Chronocast.Algorithm;
    status: Chronocast.ForecastModelStatus;
    datasetId: string;
    targetColumn: string;
    featureColumns: string[];
    hyperparameters?: Chronocast.Hyperparameters;
    metrics?: Chronocast.TrainingMetrics;
    createdAt: Date;
    trainedAt?: Date;
}
