// This file was auto-generated by Fern from our API Definition.

export interface Hyperparameters {
    learningRate?: number;
    epochs?: number;
    batchSize?: number;
    earlyStopping?: boolean;
}
