// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface Member {
    id: string;
    orgId: string;
    email: string;
    role: Chronocast.MemberRole;
    joinedAt: Date;
}
