// This file was auto-generated by Fern from our API Definition.

export const MemberRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
    Viewer: "viewer",
    _visit: <R>(value: MemberRole, visitor: MemberRole.Visitor<R>) => {
        switch (value) {
            case MemberRole.Owner:
                return visitor.owner();
            case MemberRole.Admin:
                return visitor.admin();
            case MemberRole.Member:
                return visitor.member();
            case MemberRole.Viewer:
                return visitor.viewer();
            default:
                return visitor._other();
        }
    },
} as const;
export type MemberRole = Omit<typeof MemberRole, "_visit">[keyof Omit<typeof MemberRole, "_visit">];

export namespace MemberRole {
    export interface Visitor<R> {
        owner: () => R;
        admin: () => R;
        member: () => R;
        viewer: () => R;
        _other: () => R;
    }
}
