// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface NeuralAlgorithm {
    architecture: Chronocast.NeuralAlgorithmArchitecture;
    layers: number;
    hiddenSize: number;
    dropout?: number;
}
