// This file was auto-generated by Fern from our API Definition.

export const NeuralAlgorithmArchitecture = {
    Lstm: "lstm",
    Transformer: "transformer",
    Tcn: "tcn",
    _visit: <R>(value: NeuralAlgorithmArchitecture, visitor: NeuralAlgorithmArchitecture.Visitor<R>) => {
        switch (value) {
            case NeuralAlgorithmArchitecture.Lstm:
                return visitor.lstm();
            case NeuralAlgorithmArchitecture.Transformer:
                return visitor.transformer();
            case NeuralAlgorithmArchitecture.Tcn:
                return visitor.tcn();
            default:
                return visitor._other();
        }
    },
} as const;
export type NeuralAlgorithmArchitecture = Omit<typeof NeuralAlgorithmArchitecture, "_visit">[keyof Omit<
    typeof NeuralAlgorithmArchitecture,
    "_visit"
>];

export namespace NeuralAlgorithmArchitecture {
    export interface Visitor<R> {
        lstm: () => R;
        transformer: () => R;
        tcn: () => R;
        _other: () => R;
    }
}
