// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type NotificationChannel =
    | Chronocast.NotificationChannel.Email
    | Chronocast.NotificationChannel.Slack
    | Chronocast.NotificationChannel.Webhook;

export namespace NotificationChannel {
    export interface Email extends Chronocast.EmailChannel, _Utils {
        type: "email";
    }

    export interface Slack extends Chronocast.SlackChannel, _Utils {
        type: "slack";
    }

    export interface Webhook extends Chronocast.WebhookChannel, _Utils {
        type: "webhook";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.NotificationChannel._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        email: (value: Chronocast.EmailChannel) => _Result;
        slack: (value: Chronocast.SlackChannel) => _Result;
        webhook: (value: Chronocast.WebhookChannel) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const NotificationChannel = {
    email: (value: Chronocast.EmailChannel): Chronocast.NotificationChannel.Email => {
        return {
            ...value,
            type: "email",
            _visit: function <_Result>(
                this: Chronocast.NotificationChannel.Email,
                visitor: Chronocast.NotificationChannel._Visitor<_Result>,
            ) {
                return Chronocast.NotificationChannel._visit(this, visitor);
            },
        };
    },

    slack: (value: Chronocast.SlackChannel): Chronocast.NotificationChannel.Slack => {
        return {
            ...value,
            type: "slack",
            _visit: function <_Result>(
                this: Chronocast.NotificationChannel.Slack,
                visitor: Chronocast.NotificationChannel._Visitor<_Result>,
            ) {
                return Chronocast.NotificationChannel._visit(this, visitor);
            },
        };
    },

    webhook: (value: Chronocast.WebhookChannel): Chronocast.NotificationChannel.Webhook => {
        return {
            ...value,
            type: "webhook",
            _visit: function <_Result>(
                this: Chronocast.NotificationChannel.Webhook,
                visitor: Chronocast.NotificationChannel._Visitor<_Result>,
            ) {
                return Chronocast.NotificationChannel._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: Chronocast.NotificationChannel,
        visitor: Chronocast.NotificationChannel._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "email":
                return visitor.email(value);
            case "slack":
                return visitor.slack(value);
            case "webhook":
                return visitor.webhook(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
