// This file was auto-generated by Fern from our API Definition.

export const OauthScope = {
    /**
     * Read-only access */
    Read: "read",
    /**
     * Read-write access */
    Write: "write",
    /**
     * Full admin access */
    Admin: "admin",
    _visit: <R>(value: OauthScope, visitor: OauthScope.Visitor<R>) => {
        switch (value) {
            case OauthScope.Read:
                return visitor.read();
            case OauthScope.Write:
                return visitor.write();
            case OauthScope.Admin:
                return visitor.admin();
            default:
                return visitor._other();
        }
    },
} as const;
export type OauthScope = Omit<typeof OauthScope, "_visit">[keyof Omit<typeof OauthScope, "_visit">];

export namespace OauthScope {
    export interface Visitor<R> {
        read: () => R;
        write: () => R;
        admin: () => R;
        _other: () => R;
    }
}
