// This file was auto-generated by Fern from our API Definition.

export const OrganizationPlan = {
    Free: "free",
    Pro: "pro",
    Enterprise: "enterprise",
    _visit: <R>(value: OrganizationPlan, visitor: OrganizationPlan.Visitor<R>) => {
        switch (value) {
            case OrganizationPlan.Free:
                return visitor.free();
            case OrganizationPlan.Pro:
                return visitor.pro();
            case OrganizationPlan.Enterprise:
                return visitor.enterprise();
            default:
                return visitor._other();
        }
    },
} as const;
export type OrganizationPlan = Omit<typeof OrganizationPlan, "_visit">[keyof Omit<typeof OrganizationPlan, "_visit">];

export namespace OrganizationPlan {
    export interface Visitor<R> {
        free: () => R;
        pro: () => R;
        enterprise: () => R;
        _other: () => R;
    }
}
