// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface Organization {
    id: string;
    name: string;
    slug: string;
    plan: Chronocast.OrganizationPlan;
    createdAt: Date;
    metadata?: Record<string, string | undefined>;
}
