// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface PredictionResult {
    id: string;
    modelId: string;
    horizon: number;
    createdAt: Date;
    points: Chronocast.ForecastPoint[];
}
