// This file was auto-generated by Fern from our API Definition.

export interface PredictionRequest {
    /** Number of time steps to forecast */
    horizon: number;
    confidenceIntervals?: number[];
    /** If true, results are streamed via SSE */
    streaming?: boolean;
    /** Override feature values for what-if analysis */
    inputOverrides?: Record<string, number | undefined>;
}
