// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../index.js";

export type PredictionStreamEvent =
    | Chronocast.PredictionStreamEvent.Point
    | Chronocast.PredictionStreamEvent.Progress
    | Chronocast.PredictionStreamEvent.Done
    | Chronocast.PredictionStreamEvent.Error_;

export namespace PredictionStreamEvent {
    export interface Point extends Chronocast.StreamPointEvent, _Utils {
        event: "point";
    }

    export interface Progress extends Chronocast.StreamProgressEvent, _Utils {
        event: "progress";
    }

    export interface Done extends Chronocast.StreamDoneEvent, _Utils {
        event: "done";
    }

    export interface Error_ extends Chronocast.StreamErrorEvent, _Utils {
        event: "error";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        point: (value: Chronocast.StreamPointEvent) => _Result;
        progress: (value: Chronocast.StreamProgressEvent) => _Result;
        done: (value: Chronocast.StreamDoneEvent) => _Result;
        error: (value: Chronocast.StreamErrorEvent) => _Result;
        _other: (value: { event: string }) => _Result;
    }
}

export const PredictionStreamEvent = {
    point: (value: Chronocast.StreamPointEvent): Chronocast.PredictionStreamEvent.Point => {
        return {
            ...value,
            event: "point",
            _visit: function <_Result>(
                this: Chronocast.PredictionStreamEvent.Point,
                visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>,
            ) {
                return Chronocast.PredictionStreamEvent._visit(this, visitor);
            },
        };
    },

    progress: (value: Chronocast.StreamProgressEvent): Chronocast.PredictionStreamEvent.Progress => {
        return {
            ...value,
            event: "progress",
            _visit: function <_Result>(
                this: Chronocast.PredictionStreamEvent.Progress,
                visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>,
            ) {
                return Chronocast.PredictionStreamEvent._visit(this, visitor);
            },
        };
    },

    done: (value: Chronocast.StreamDoneEvent): Chronocast.PredictionStreamEvent.Done => {
        return {
            ...value,
            event: "done",
            _visit: function <_Result>(
                this: Chronocast.PredictionStreamEvent.Done,
                visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>,
            ) {
                return Chronocast.PredictionStreamEvent._visit(this, visitor);
            },
        };
    },

    error: (value: Chronocast.StreamErrorEvent): Chronocast.PredictionStreamEvent.Error_ => {
        return {
            ...value,
            event: "error",
            _visit: function <_Result>(
                this: Chronocast.PredictionStreamEvent.Error_,
                visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>,
            ) {
                return Chronocast.PredictionStreamEvent._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: Chronocast.PredictionStreamEvent,
        visitor: Chronocast.PredictionStreamEvent._Visitor<_Result>,
    ): _Result => {
        switch (value.event) {
            case "point":
                return visitor.point(value);
            case "progress":
                return visitor.progress(value);
            case "done":
                return visitor.done(value);
            case "error":
                return visitor.error(value);
            default:
                return visitor._other(value);
        }
    },
} as const;
