// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface ThresholdCondition {
    metric: string;
    operator: Chronocast.ThresholdConditionOperator;
    value: number;
    durationMinutes: number;
}
