// This file was auto-generated by Fern from our API Definition.

export const ThresholdConditionOperator = {
    Gt: "gt",
    Gte: "gte",
    Lt: "lt",
    Lte: "lte",
    Eq: "eq",
    _visit: <R>(value: ThresholdConditionOperator, visitor: ThresholdConditionOperator.Visitor<R>) => {
        switch (value) {
            case ThresholdConditionOperator.Gt:
                return visitor.gt();
            case ThresholdConditionOperator.Gte:
                return visitor.gte();
            case ThresholdConditionOperator.Lt:
                return visitor.lt();
            case ThresholdConditionOperator.Lte:
                return visitor.lte();
            case ThresholdConditionOperator.Eq:
                return visitor.eq();
            default:
                return visitor._other();
        }
    },
} as const;
export type ThresholdConditionOperator = Omit<typeof ThresholdConditionOperator, "_visit">[keyof Omit<
    typeof ThresholdConditionOperator,
    "_visit"
>];

export namespace ThresholdConditionOperator {
    export interface Visitor<R> {
        gt: () => R;
        gte: () => R;
        lt: () => R;
        lte: () => R;
        eq: () => R;
        _other: () => R;
    }
}
