// This file was auto-generated by Fern from our API Definition.

export interface TrainingMetrics {
    /** Mean absolute error */
    mae: number;
    /** Root mean squared error */
    rmse: number;
    /** Mean absolute percentage error */
    mape: number;
    rSquared: number;
    trainingDurationSeconds: number;
}
