// This file was auto-generated by Fern from our API Definition.

export const TrendConditionDirection = {
    Increasing: "increasing",
    Decreasing: "decreasing",
    Either: "either",
    _visit: <R>(value: TrendConditionDirection, visitor: TrendConditionDirection.Visitor<R>) => {
        switch (value) {
            case TrendConditionDirection.Increasing:
                return visitor.increasing();
            case TrendConditionDirection.Decreasing:
                return visitor.decreasing();
            case TrendConditionDirection.Either:
                return visitor.either();
            default:
                return visitor._other();
        }
    },
} as const;
export type TrendConditionDirection = Omit<typeof TrendConditionDirection, "_visit">[keyof Omit<
    typeof TrendConditionDirection,
    "_visit"
>];

export namespace TrendConditionDirection {
    export interface Visitor<R> {
        increasing: () => R;
        decreasing: () => R;
        either: () => R;
        _other: () => R;
    }
}
