// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface TrendCondition {
    direction: Chronocast.TrendConditionDirection;
    slopeThreshold: number;
    windowSize: number;
}
