// This file was auto-generated by Fern from our API Definition.

export const WebhookEndpointEventsItem = {
    ModelTrainingStarted: "model.training.started",
    ModelTrainingCompleted: "model.training.completed",
    ModelTrainingFailed: "model.training.failed",
    PredictionCompleted: "prediction.completed",
    AlertTriggered: "alert.triggered",
    AlertResolved: "alert.resolved",
    DatasetReady: "dataset.ready",
    DatasetFailed: "dataset.failed",
    _visit: <R>(value: WebhookEndpointEventsItem, visitor: WebhookEndpointEventsItem.Visitor<R>) => {
        switch (value) {
            case WebhookEndpointEventsItem.ModelTrainingStarted:
                return visitor.modelTrainingStarted();
            case WebhookEndpointEventsItem.ModelTrainingCompleted:
                return visitor.modelTrainingCompleted();
            case WebhookEndpointEventsItem.ModelTrainingFailed:
                return visitor.modelTrainingFailed();
            case WebhookEndpointEventsItem.PredictionCompleted:
                return visitor.predictionCompleted();
            case WebhookEndpointEventsItem.AlertTriggered:
                return visitor.alertTriggered();
            case WebhookEndpointEventsItem.AlertResolved:
                return visitor.alertResolved();
            case WebhookEndpointEventsItem.DatasetReady:
                return visitor.datasetReady();
            case WebhookEndpointEventsItem.DatasetFailed:
                return visitor.datasetFailed();
            default:
                return visitor._other();
        }
    },
} as const;
export type WebhookEndpointEventsItem = Omit<typeof WebhookEndpointEventsItem, "_visit">[keyof Omit<
    typeof WebhookEndpointEventsItem,
    "_visit"
>];

export namespace WebhookEndpointEventsItem {
    export interface Visitor<R> {
        modelTrainingStarted: () => R;
        modelTrainingCompleted: () => R;
        modelTrainingFailed: () => R;
        predictionCompleted: () => R;
        alertTriggered: () => R;
        alertResolved: () => R;
        datasetReady: () => R;
        datasetFailed: () => R;
        _other: () => R;
    }
}
