// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../index.js";

export interface WebhookEndpoint {
    id: string;
    url: string;
    events: Chronocast.WebhookEndpointEventsItem[];
    /** HMAC-SHA256 signing secret (only returned on creation) */
    secret?: string;
    active: boolean;
    createdAt: Date;
}
