// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         name: "name"
 *     }
 */
export interface ProjectCreate {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    name: string;
    description?: string;
}
