// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Organization } from "../../../types/Organization.js";

export const ListOrganizationsResponse: core.serialization.ObjectSchema<
    serializers.ListOrganizationsResponse.Raw,
    Chronocast.ListOrganizationsResponse
> = core.serialization.object({
    data: core.serialization.list(Organization).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListOrganizationsResponse {
    export interface Raw {
        data?: Organization.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
