// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const OrganizationCreatePlan: core.serialization.Schema<
    serializers.OrganizationCreatePlan.Raw,
    Chronocast.OrganizationCreatePlan
> = core.serialization.enum_(["free", "pro", "enterprise"]);

export declare namespace OrganizationCreatePlan {
    export type Raw = "free" | "pro" | "enterprise";
}
