// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { WebhookEndpoint } from "../../../types/WebhookEndpoint.js";

export const ListWebhooksResponse: core.serialization.ObjectSchema<
    serializers.ListWebhooksResponse.Raw,
    Chronocast.ListWebhooksResponse
> = core.serialization.object({
    data: core.serialization.list(WebhookEndpoint).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListWebhooksResponse {
    export interface Raw {
        data?: WebhookEndpoint.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
