// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { WebhookDelivery } from "../../../types/WebhookDelivery.js";

export const ListWebhookDeliveriesResponse: core.serialization.ObjectSchema<
    serializers.ListWebhookDeliveriesResponse.Raw,
    Chronocast.ListWebhookDeliveriesResponse
> = core.serialization.object({
    data: core.serialization.list(WebhookDelivery).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListWebhookDeliveriesResponse {
    export interface Raw {
        data?: WebhookDelivery.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
