// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const VerifyWebhookSignatureResponse: core.serialization.ObjectSchema<
    serializers.VerifyWebhookSignatureResponse.Raw,
    Chronocast.VerifyWebhookSignatureResponse
> = core.serialization.object({
    valid: core.serialization.boolean(),
    reason: core.serialization.string().optional(),
});

export declare namespace VerifyWebhookSignatureResponse {
    export interface Raw {
        valid: boolean;
        reason?: string | null;
    }
}
