// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const WebhookEndpointCreateEventsItem: core.serialization.Schema<
    serializers.WebhookEndpointCreateEventsItem.Raw,
    Chronocast.WebhookEndpointCreateEventsItem
> = core.serialization.enum_([
    "model.training.started",
    "model.training.completed",
    "model.training.failed",
    "prediction.completed",
    "alert.triggered",
    "alert.resolved",
    "dataset.ready",
    "dataset.failed",
]);

export declare namespace WebhookEndpointCreateEventsItem {
    export type Raw =
        | "model.training.started"
        | "model.training.completed"
        | "model.training.failed"
        | "prediction.completed"
        | "alert.triggered"
        | "alert.resolved"
        | "dataset.ready"
        | "dataset.failed";
}
