// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListMembersRequestRole: core.serialization.Schema<
    serializers.ListMembersRequestRole.Raw,
    Chronocast.ListMembersRequestRole
> = core.serialization.enum_(["owner", "admin", "member", "viewer"]);

export declare namespace ListMembersRequestRole {
    export type Raw = "owner" | "admin" | "member" | "viewer";
}
