// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Member } from "../../../types/Member.js";

export const ListMembersResponse: core.serialization.ObjectSchema<
    serializers.ListMembersResponse.Raw,
    Chronocast.ListMembersResponse
> = core.serialization.object({
    data: core.serialization.list(Member).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListMembersResponse {
    export interface Raw {
        data?: Member.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
