// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const MemberInviteRole: core.serialization.Schema<
    serializers.MemberInviteRole.Raw,
    Chronocast.MemberInviteRole
> = core.serialization.enum_(["admin", "member", "viewer"]);

export declare namespace MemberInviteRole {
    export type Raw = "admin" | "member" | "viewer";
}
