// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AlertCondition } from "../../../../types/AlertCondition.js";
import { NotificationChannel } from "../../../../types/NotificationChannel.js";

export const AlertCreate: core.serialization.Schema<
    serializers.AlertCreate.Raw,
    Omit<Chronocast.AlertCreate, "idempotencyKey">
> = core.serialization.object({
    name: core.serialization.string(),
    modelId: core.serialization.property("model_id", core.serialization.string()),
    condition: AlertCondition,
    channels: core.serialization.list(NotificationChannel),
    enabled: core.serialization.boolean().optional(),
});

export declare namespace AlertCreate {
    export interface Raw {
        name: string;
        model_id: string;
        condition: AlertCondition.Raw;
        channels: NotificationChannel.Raw[];
        enabled?: boolean | null;
    }
}
