// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AlertCondition } from "../../../../types/AlertCondition.js";
import { NotificationChannel } from "../../../../types/NotificationChannel.js";

export const UpdateAlertRequest: core.serialization.Schema<
    serializers.UpdateAlertRequest.Raw,
    Chronocast.UpdateAlertRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    condition: AlertCondition.optional(),
    channels: core.serialization.list(NotificationChannel).optional(),
    enabled: core.serialization.boolean().optional(),
});

export declare namespace UpdateAlertRequest {
    export interface Raw {
        name?: string | null;
        condition?: AlertCondition.Raw | null;
        channels?: NotificationChannel.Raw[] | null;
        enabled?: boolean | null;
    }
}
