// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Chronocast from "../../../index.js";

export declare namespace ModelsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create, train, and manage forecast models
 */
export class ModelsClient {
    protected readonly _options: NormalizedClientOptions<ModelsClient.Options>;

    constructor(options: ModelsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {Chronocast.ListModelsRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.models.listModels("org_id", "project_id", {
     *         cursor: "cursor",
     *         limit: 1,
     *         status: "draft"
     *     })
     */
    public listModels(
        org_id: string,
        project_id: string,
        request: Chronocast.ListModelsRequest = {},
        requestOptions?: ModelsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ListModelsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listModels(org_id, project_id, request, requestOptions));
    }

    private async __listModels(
        org_id: string,
        project_id: string,
        request: Chronocast.ListModelsRequest = {},
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ListModelsResponse>> {
        const { cursor, limit, status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (status != null) {
            _queryParams.status = serializers.ListModelsRequestStatus.jsonOrThrow(status, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            });
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/models`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListModelsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}/models.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {Chronocast.ModelCreate} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.BadRequestError}
     *
     * @example
     *     await client.models.createModel("org_id", "project_id", {
     *         idempotencyKey: "Idempotency-Key",
     *         name: "name",
     *         algorithm: Chronocast.Algorithm.arima({
     *             orderP: 1,
     *             orderD: 1,
     *             orderQ: 1
     *         }),
     *         datasetId: "dataset_id",
     *         targetColumn: "target_column",
     *         featureColumns: ["feature_columns"]
     *     })
     */
    public createModel(
        org_id: string,
        project_id: string,
        request: Chronocast.ModelCreate,
        requestOptions?: ModelsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ForecastModel> {
        return core.HttpResponsePromise.fromPromise(this.__createModel(org_id, project_id, request, requestOptions));
    }

    private async __createModel(
        org_id: string,
        project_id: string,
        request: Chronocast.ModelCreate,
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ForecastModel>> {
        const { idempotencyKey, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/models`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.ModelCreate.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip", omitUndefined: true }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ForecastModel.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Chronocast.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling POST /organizations/{org_id}/projects/{project_id}/models.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} model_id
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.NotFoundError}
     *
     * @example
     *     await client.models.getModel("org_id", "project_id", "model_id")
     */
    public getModel(
        org_id: string,
        project_id: string,
        model_id: string,
        requestOptions?: ModelsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ForecastModel> {
        return core.HttpResponsePromise.fromPromise(this.__getModel(org_id, project_id, model_id, requestOptions));
    }

    private async __getModel(
        org_id: string,
        project_id: string,
        model_id: string,
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ForecastModel>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/models/${core.url.encodePathParam(model_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ForecastModel.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Chronocast.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}/models/{model_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} model_id
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.models.deleteModel("org_id", "project_id", "model_id")
     */
    public deleteModel(
        org_id: string,
        project_id: string,
        model_id: string,
        requestOptions?: ModelsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteModel(org_id, project_id, model_id, requestOptions));
    }

    private async __deleteModel(
        org_id: string,
        project_id: string,
        model_id: string,
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/models/${core.url.encodePathParam(model_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling DELETE /organizations/{org_id}/projects/{project_id}/models/{model_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} model_id
     * @param {Chronocast.TrainModelRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.BadRequestError}
     * @throws {@link Chronocast.NotFoundError}
     *
     * @example
     *     await client.models.trainModel("org_id", "project_id", "model_id", {
     *         idempotencyKey: "Idempotency-Key"
     *     })
     */
    public trainModel(
        org_id: string,
        project_id: string,
        model_id: string,
        request: Chronocast.TrainModelRequest = {},
        requestOptions?: ModelsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.AsyncOperation> {
        return core.HttpResponsePromise.fromPromise(
            this.__trainModel(org_id, project_id, model_id, request, requestOptions),
        );
    }

    private async __trainModel(
        org_id: string,
        project_id: string,
        model_id: string,
        request: Chronocast.TrainModelRequest = {},
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.AsyncOperation>> {
        const { idempotencyKey, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/models/${core.url.encodePathParam(model_id)}/train`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.TrainModelRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.AsyncOperation.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Chronocast.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Chronocast.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling POST /organizations/{org_id}/projects/{project_id}/models/{model_id}/train.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
