// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Chronocast from "../../../index.js";

export declare namespace AlertsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Configure anomaly alerts and view history
 */
export class AlertsClient {
    protected readonly _options: NormalizedClientOptions<AlertsClient.Options>;

    constructor(options: AlertsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {Chronocast.ListAlertsRequest} request
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.alerts.listAlerts("org_id", "project_id", {
     *         cursor: "cursor",
     *         limit: 1
     *     })
     */
    public listAlerts(
        org_id: string,
        project_id: string,
        request: Chronocast.ListAlertsRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ListAlertsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAlerts(org_id, project_id, request, requestOptions));
    }

    private async __listAlerts(
        org_id: string,
        project_id: string,
        request: Chronocast.ListAlertsRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ListAlertsResponse>> {
        const { cursor, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListAlertsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}/alerts.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {Chronocast.AlertCreate} request
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.alerts.createAlert("org_id", "project_id", {
     *         idempotencyKey: "Idempotency-Key",
     *         name: "name",
     *         modelId: "model_id",
     *         condition: Chronocast.AlertCondition.threshold({
     *             metric: "metric",
     *             operator: "gt",
     *             value: 1.1,
     *             durationMinutes: 1
     *         }),
     *         channels: [Chronocast.NotificationChannel.email({
     *                 address: "address"
     *             })]
     *     })
     */
    public createAlert(
        org_id: string,
        project_id: string,
        request: Chronocast.AlertCreate,
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Alert> {
        return core.HttpResponsePromise.fromPromise(this.__createAlert(org_id, project_id, request, requestOptions));
    }

    private async __createAlert(
        org_id: string,
        project_id: string,
        request: Chronocast.AlertCreate,
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Alert>> {
        const { idempotencyKey, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.AlertCreate.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip", omitUndefined: true }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Alert.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling POST /organizations/{org_id}/projects/{project_id}/alerts.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} alert_id
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.NotFoundError}
     *
     * @example
     *     await client.alerts.getAlert("org_id", "project_id", "alert_id")
     */
    public getAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Alert> {
        return core.HttpResponsePromise.fromPromise(this.__getAlert(org_id, project_id, alert_id, requestOptions));
    }

    private async __getAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Alert>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts/${core.url.encodePathParam(alert_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Alert.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Chronocast.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}/alerts/{alert_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} alert_id
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.alerts.deleteAlert("org_id", "project_id", "alert_id")
     */
    public deleteAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAlert(org_id, project_id, alert_id, requestOptions));
    }

    private async __deleteAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts/${core.url.encodePathParam(alert_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling DELETE /organizations/{org_id}/projects/{project_id}/alerts/{alert_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} alert_id
     * @param {Chronocast.UpdateAlertRequest} request
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.alerts.updateAlert("org_id", "project_id", "alert_id")
     */
    public updateAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        request: Chronocast.UpdateAlertRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Alert> {
        return core.HttpResponsePromise.fromPromise(
            this.__updateAlert(org_id, project_id, alert_id, request, requestOptions),
        );
    }

    private async __updateAlert(
        org_id: string,
        project_id: string,
        alert_id: string,
        request: Chronocast.UpdateAlertRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Alert>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts/${core.url.encodePathParam(alert_id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.UpdateAlertRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Alert.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling PATCH /organizations/{org_id}/projects/{project_id}/alerts/{alert_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {string} alert_id
     * @param {Chronocast.ListAlertHistoryRequest} request
     * @param {AlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.alerts.listAlertHistory("org_id", "project_id", "alert_id", {
     *         offset: 1,
     *         limit: 1,
     *         since: new Date("2024-01-15T09:30:00.000Z"),
     *         until: new Date("2024-01-15T09:30:00.000Z")
     *     })
     */
    public listAlertHistory(
        org_id: string,
        project_id: string,
        alert_id: string,
        request: Chronocast.ListAlertHistoryRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ListAlertHistoryResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__listAlertHistory(org_id, project_id, alert_id, request, requestOptions),
        );
    }

    private async __listAlertHistory(
        org_id: string,
        project_id: string,
        alert_id: string,
        request: Chronocast.ListAlertHistoryRequest = {},
        requestOptions?: AlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ListAlertHistoryResponse>> {
        const { offset, limit, since, until } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (offset != null) {
            _queryParams.offset = offset.toString();
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (since != null) {
            _queryParams.since = since.toISOString();
        }

        if (until != null) {
            _queryParams.until = until.toISOString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}/alerts/${core.url.encodePathParam(alert_id)}/history`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListAlertHistoryResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}/alerts/{alert_id}/history.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
