// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Chronocast from "../index.js";

export class TooManyRequestsError extends errors.ChronocastError {
    constructor(body: Chronocast.ApiError, rawResponse?: core.RawResponse) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, TooManyRequestsError.prototype);
    }
}
