// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Alert } from "../../../types/Alert.js";

export const ListAlertsResponse: core.serialization.ObjectSchema<
    serializers.ListAlertsResponse.Raw,
    Chronocast.ListAlertsResponse
> = core.serialization.object({
    data: core.serialization.list(Alert).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListAlertsResponse {
    export interface Raw {
        data?: Alert.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
