// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AlertEvent } from "../../../types/AlertEvent.js";

export const ListAlertHistoryResponse: core.serialization.ObjectSchema<
    serializers.ListAlertHistoryResponse.Raw,
    Chronocast.ListAlertHistoryResponse
> = core.serialization.object({
    data: core.serialization.list(AlertEvent).optional(),
    total: core.serialization.number(),
    offset: core.serialization.number(),
    limit: core.serialization.number(),
});

export declare namespace ListAlertHistoryResponse {
    export interface Raw {
        data?: AlertEvent.Raw[] | null;
        total: number;
        offset: number;
        limit: number;
    }
}
