// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         name: "name",
 *         slug: "slug"
 *     }
 */
export interface OrganizationCreate {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    name: string;
    slug: string;
    plan?: Chronocast.OrganizationCreatePlan;
    metadata?: Record<string, string>;
}
