// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateOrganizationRequest {
    name?: string;
    plan?: Chronocast.UpdateOrganizationRequestPlan;
    metadata?: Record<string, string | undefined>;
}
