// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AlertCondition } from "./AlertCondition.js";
import { NotificationChannel } from "./NotificationChannel.js";

export const Alert: core.serialization.ObjectSchema<serializers.Alert.Raw, Chronocast.Alert> =
    core.serialization.object({
        id: core.serialization.string(),
        projectId: core.serialization.property("project_id", core.serialization.string()),
        name: core.serialization.string(),
        modelId: core.serialization.property("model_id", core.serialization.string()),
        condition: AlertCondition,
        channels: core.serialization.list(NotificationChannel),
        enabled: core.serialization.boolean(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace Alert {
    export interface Raw {
        id: string;
        project_id: string;
        name: string;
        model_id: string;
        condition: AlertCondition.Raw;
        channels: NotificationChannel.Raw[];
        enabled: boolean;
        created_at: string;
    }
}
