// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AlertCondition } from "./AlertCondition.js";

export const AlertEvent: core.serialization.ObjectSchema<serializers.AlertEvent.Raw, Chronocast.AlertEvent> =
    core.serialization.object({
        id: core.serialization.string(),
        alertId: core.serialization.property("alert_id", core.serialization.string()),
        triggeredAt: core.serialization.property("triggered_at", core.serialization.date()),
        conditionSnapshot: core.serialization.property("condition_snapshot", AlertCondition),
        observedValue: core.serialization.property("observed_value", core.serialization.number()),
        resolvedAt: core.serialization.property("resolved_at", core.serialization.date().optional()),
    });

export declare namespace AlertEvent {
    export interface Raw {
        id: string;
        alert_id: string;
        triggered_at: string;
        condition_snapshot: AlertCondition.Raw;
        observed_value: number;
        resolved_at?: string | null;
    }
}
