// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AnomalyCondition } from "./AnomalyCondition.js";
import { ThresholdCondition } from "./ThresholdCondition.js";
import { TrendCondition } from "./TrendCondition.js";

export const AlertCondition: core.serialization.Schema<serializers.AlertCondition.Raw, Chronocast.AlertCondition> =
    core.serialization
        .union("type", {
            threshold: ThresholdCondition,
            anomaly: AnomalyCondition,
            trend: TrendCondition,
        })
        .transform<Chronocast.AlertCondition>({
            transform: (value) => {
                switch (value.type) {
                    case "threshold":
                        return Chronocast.AlertCondition.threshold(value);
                    case "anomaly":
                        return Chronocast.AlertCondition.anomaly(value);
                    case "trend":
                        return Chronocast.AlertCondition.trend(value);
                    default:
                        return value as Chronocast.AlertCondition;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace AlertCondition {
    export type Raw = AlertCondition.Threshold | AlertCondition.Anomaly | AlertCondition.Trend;

    export interface Threshold extends ThresholdCondition.Raw {
        type: "threshold";
    }

    export interface Anomaly extends AnomalyCondition.Raw {
        type: "anomaly";
    }

    export interface Trend extends TrendCondition.Raw {
        type: "trend";
    }
}
