// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { ArimaAlgorithm } from "./ArimaAlgorithm.js";
import { NeuralAlgorithm } from "./NeuralAlgorithm.js";

export const Algorithm: core.serialization.Schema<serializers.Algorithm.Raw, Chronocast.Algorithm> = core.serialization
    .union("type", {
        arima: ArimaAlgorithm,
        neural: NeuralAlgorithm,
        ensemble: core.serialization.lazyObject(() => serializers.EnsembleAlgorithm),
    })
    .transform<Chronocast.Algorithm>({
        transform: (value) => {
            switch (value.type) {
                case "arima":
                    return Chronocast.Algorithm.arima(value);
                case "neural":
                    return Chronocast.Algorithm.neural(value);
                case "ensemble":
                    return Chronocast.Algorithm.ensemble(value);
                default:
                    return value as Chronocast.Algorithm;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace Algorithm {
    export type Raw = Algorithm.Arima | Algorithm.Neural | Algorithm.Ensemble;

    export interface Arima extends ArimaAlgorithm.Raw {
        type: "arima";
    }

    export interface Neural extends NeuralAlgorithm.Raw {
        type: "neural";
    }

    export interface Ensemble extends serializers.EnsembleAlgorithm.Raw {
        type: "ensemble";
    }
}
