// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AnomalyCondition: core.serialization.ObjectSchema<
    serializers.AnomalyCondition.Raw,
    Chronocast.AnomalyCondition
> = core.serialization.object({
    sensitivity: core.serialization.number(),
    minDeviationPct: core.serialization.property("min_deviation_pct", core.serialization.number().optional()),
});

export declare namespace AnomalyCondition {
    export interface Raw {
        sensitivity: number;
        min_deviation_pct?: number | null;
    }
}
