// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ApiErrorType: core.serialization.Schema<serializers.ApiErrorType.Raw, Chronocast.ApiErrorType> =
    core.serialization.enum_([
        "invalid_request",
        "authentication_error",
        "permission_denied",
        "not_found",
        "rate_limit",
        "conflict",
        "internal_error",
    ]);

export declare namespace ApiErrorType {
    export type Raw =
        | "invalid_request"
        | "authentication_error"
        | "permission_denied"
        | "not_found"
        | "rate_limit"
        | "conflict"
        | "internal_error";
}
