// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApiErrorType } from "./ApiErrorType.js";
import { FieldError } from "./FieldError.js";

export const ApiError: core.serialization.ObjectSchema<serializers.ApiError.Raw, Chronocast.ApiError> =
    core.serialization.object({
        type: ApiErrorType,
        message: core.serialization.string(),
        requestId: core.serialization.property("request_id", core.serialization.string()),
        details: core.serialization.list(FieldError).optional(),
    });

export declare namespace ApiError {
    export interface Raw {
        type: ApiErrorType.Raw;
        message: string;
        request_id: string;
        details?: FieldError.Raw[] | null;
    }
}
