// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ApiPullSource: core.serialization.ObjectSchema<serializers.ApiPullSource.Raw, Chronocast.ApiPullSource> =
    core.serialization.object({
        sourceUrl: core.serialization.property("source_url", core.serialization.string()),
        scheduleCron: core.serialization.property("schedule_cron", core.serialization.string()),
        headers: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    });

export declare namespace ApiPullSource {
    export interface Raw {
        source_url: string;
        schedule_cron: string;
        headers?: Record<string, string> | null;
    }
}
