// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ArimaAlgorithm: core.serialization.ObjectSchema<
    serializers.ArimaAlgorithm.Raw,
    Chronocast.ArimaAlgorithm
> = core.serialization.object({
    orderP: core.serialization.property("order_p", core.serialization.number()),
    orderD: core.serialization.property("order_d", core.serialization.number()),
    orderQ: core.serialization.property("order_q", core.serialization.number()),
    seasonal: core.serialization.boolean().optional(),
});

export declare namespace ArimaAlgorithm {
    export interface Raw {
        order_p: number;
        order_d: number;
        order_q: number;
        seasonal?: boolean | null;
    }
}
