// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AsyncOperationStatus } from "./AsyncOperationStatus.js";
import { OperationError } from "./OperationError.js";

export const AsyncOperation: core.serialization.ObjectSchema<
    serializers.AsyncOperation.Raw,
    Chronocast.AsyncOperation
> = core.serialization.object({
    id: core.serialization.string(),
    status: AsyncOperationStatus,
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    resultUrl: core.serialization.property("result_url", core.serialization.string().optional()),
    error: OperationError.optional(),
    progressPct: core.serialization.property("progress_pct", core.serialization.number().optional()),
});

export declare namespace AsyncOperation {
    export interface Raw {
        id: string;
        status: AsyncOperationStatus.Raw;
        created_at: string;
        updated_at: string;
        result_url?: string | null;
        error?: OperationError.Raw | null;
        progress_pct?: number | null;
    }
}
