// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AsyncOperationStatus: core.serialization.Schema<
    serializers.AsyncOperationStatus.Raw,
    Chronocast.AsyncOperationStatus
> = core.serialization.enum_(["pending", "running", "succeeded", "failed", "cancelled"]);

export declare namespace AsyncOperationStatus {
    export type Raw = "pending" | "running" | "succeeded" | "failed" | "cancelled";
}
