// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BatchItemError } from "./BatchItemError.js";
import { PredictionResult } from "./PredictionResult.js";

export const BatchPredictionResponseResultsItem: core.serialization.Schema<
    serializers.BatchPredictionResponseResultsItem.Raw,
    Chronocast.BatchPredictionResponseResultsItem
> = core.serialization
    .union(core.serialization.discriminant("resultType", "result_type"), {
        result: PredictionResult,
        error: BatchItemError,
    })
    .transform<Chronocast.BatchPredictionResponseResultsItem>({
        transform: (value) => {
            switch (value.resultType) {
                case "result":
                    return Chronocast.BatchPredictionResponseResultsItem.result(value);
                case "error":
                    return Chronocast.BatchPredictionResponseResultsItem.error(value);
                default:
                    return value as Chronocast.BatchPredictionResponseResultsItem;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace BatchPredictionResponseResultsItem {
    export type Raw = BatchPredictionResponseResultsItem.Result | BatchPredictionResponseResultsItem.Error;

    export interface Result extends PredictionResult.Raw {
        result_type: "result";
    }

    export interface Error extends BatchItemError.Raw {
        result_type: "error";
    }
}
