// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BatchItemError: core.serialization.ObjectSchema<
    serializers.BatchItemError.Raw,
    Chronocast.BatchItemError
> = core.serialization.object({
    index: core.serialization.number(),
    code: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace BatchItemError {
    export interface Raw {
        index: number;
        code: string;
        message: string;
    }
}
