// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BatchPredictionResponseResultsItem } from "./BatchPredictionResponseResultsItem.js";

export const BatchPredictionResponse: core.serialization.ObjectSchema<
    serializers.BatchPredictionResponse.Raw,
    Chronocast.BatchPredictionResponse
> = core.serialization.object({
    id: core.serialization.string(),
    results: core.serialization.list(BatchPredictionResponseResultsItem),
});

export declare namespace BatchPredictionResponse {
    export interface Raw {
        id: string;
        results: BatchPredictionResponseResultsItem.Raw[];
    }
}
