// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ColumnSchemaDtype: core.serialization.Schema<
    serializers.ColumnSchemaDtype.Raw,
    Chronocast.ColumnSchemaDtype
> = core.serialization.enum_(["float64", "int64", "string", "datetime", "boolean"]);

export declare namespace ColumnSchemaDtype {
    export type Raw = "float64" | "int64" | "string" | "datetime" | "boolean";
}
