// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ColumnSchemaDtype } from "./ColumnSchemaDtype.js";

export const ColumnSchema: core.serialization.ObjectSchema<serializers.ColumnSchema.Raw, Chronocast.ColumnSchema> =
    core.serialization.object({
        name: core.serialization.string(),
        dtype: ColumnSchemaDtype,
        nullable: core.serialization.boolean(),
    });

export declare namespace ColumnSchema {
    export interface Raw {
        name: string;
        dtype: ColumnSchemaDtype.Raw;
        nullable: boolean;
    }
}
