// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfidenceInterval: core.serialization.ObjectSchema<
    serializers.ConfidenceInterval.Raw,
    Chronocast.ConfidenceInterval
> = core.serialization.object({
    level: core.serialization.number(),
    lower: core.serialization.number(),
    upper: core.serialization.number(),
});

export declare namespace ConfidenceInterval {
    export interface Raw {
        level: number;
        lower: number;
        upper: number;
    }
}
