// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CursorPage: core.serialization.ObjectSchema<serializers.CursorPage.Raw, Chronocast.CursorPage> =
    core.serialization.object({
        hasMore: core.serialization.property("has_more", core.serialization.boolean()),
        nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
        data: core.serialization.list(core.serialization.unknown()),
    });

export declare namespace CursorPage {
    export interface Raw {
        has_more: boolean;
        next_cursor?: string | null;
        data: unknown[];
    }
}
