// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DatasetStatus: core.serialization.Schema<serializers.DatasetStatus.Raw, Chronocast.DatasetStatus> =
    core.serialization.enum_(["uploading", "processing", "ready", "failed"]);

export declare namespace DatasetStatus {
    export type Raw = "uploading" | "processing" | "ready" | "failed";
}
