// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DatasetFormat: core.serialization.Schema<serializers.DatasetFormat.Raw, Chronocast.DatasetFormat> =
    core.serialization.enum_(["csv", "parquet", "json"]);

export declare namespace DatasetFormat {
    export type Raw = "csv" | "parquet" | "json";
}
