// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApiPullSource } from "./ApiPullSource.js";
import { FileUploadSource } from "./FileUploadSource.js";
import { WebhookIngestSource } from "./WebhookIngestSource.js";

export const DataSource: core.serialization.Schema<serializers.DataSource.Raw, Chronocast.DataSource> =
    core.serialization
        .union("type", {
            file_upload: FileUploadSource,
            webhook_ingest: WebhookIngestSource,
            api_pull: ApiPullSource,
        })
        .transform<Chronocast.DataSource>({
            transform: (value) => {
                switch (value.type) {
                    case "file_upload":
                        return Chronocast.DataSource.fileUpload(value);
                    case "webhook_ingest":
                        return Chronocast.DataSource.webhookIngest(value);
                    case "api_pull":
                        return Chronocast.DataSource.apiPull(value);
                    default:
                        return value as Chronocast.DataSource;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace DataSource {
    export type Raw = DataSource.FileUpload | DataSource.WebhookIngest | DataSource.ApiPull;

    export interface FileUpload extends FileUploadSource.Raw {
        type: "file_upload";
    }

    export interface WebhookIngest extends WebhookIngestSource.Raw {
        type: "webhook_ingest";
    }

    export interface ApiPull extends ApiPullSource.Raw {
        type: "api_pull";
    }
}
