// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmailChannel: core.serialization.ObjectSchema<serializers.EmailChannel.Raw, Chronocast.EmailChannel> =
    core.serialization.object({
        address: core.serialization.string(),
    });

export declare namespace EmailChannel {
    export interface Raw {
        address: string;
    }
}
