// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EnsembleAlgorithmCombinationMethod: core.serialization.Schema<
    serializers.EnsembleAlgorithmCombinationMethod.Raw,
    Chronocast.EnsembleAlgorithmCombinationMethod
> = core.serialization.enum_(["average", "weighted", "stacking"]);

export declare namespace EnsembleAlgorithmCombinationMethod {
    export type Raw = "average" | "weighted" | "stacking";
}
