// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { EnsembleAlgorithmCombinationMethod } from "./EnsembleAlgorithmCombinationMethod.js";

export const EnsembleAlgorithm: core.serialization.ObjectSchema<
    serializers.EnsembleAlgorithm.Raw,
    Chronocast.EnsembleAlgorithm
> = core.serialization.object({
    subAlgorithms: core.serialization.property(
        "sub_algorithms",
        core.serialization.list(core.serialization.lazy(() => serializers.Algorithm)),
    ),
    combinationMethod: core.serialization.property("combination_method", EnsembleAlgorithmCombinationMethod),
});

export declare namespace EnsembleAlgorithm {
    export interface Raw {
        sub_algorithms: serializers.Algorithm.Raw[];
        combination_method: EnsembleAlgorithmCombinationMethod.Raw;
    }
}
