// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FieldErrorCode: core.serialization.Schema<serializers.FieldErrorCode.Raw, Chronocast.FieldErrorCode> =
    core.serialization.enum_([
        "required",
        "invalid_format",
        "out_of_range",
        "too_long",
        "too_short",
        "unique_violation",
    ]);

export declare namespace FieldErrorCode {
    export type Raw = "required" | "invalid_format" | "out_of_range" | "too_long" | "too_short" | "unique_violation";
}
