// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FieldErrorCode } from "./FieldErrorCode.js";

export const FieldError: core.serialization.ObjectSchema<serializers.FieldError.Raw, Chronocast.FieldError> =
    core.serialization.object({
        field: core.serialization.string(),
        message: core.serialization.string(),
        code: FieldErrorCode,
    });

export declare namespace FieldError {
    export interface Raw {
        field: string;
        message: string;
        code: FieldErrorCode.Raw;
    }
}
