// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FileUploadSource: core.serialization.ObjectSchema<
    serializers.FileUploadSource.Raw,
    Chronocast.FileUploadSource
> = core.serialization.object({
    filename: core.serialization.string(),
    contentType: core.serialization.property("content_type", core.serialization.string()),
});

export declare namespace FileUploadSource {
    export interface Raw {
        filename: string;
        content_type: string;
    }
}
