// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfidenceInterval } from "./ConfidenceInterval.js";

export const ForecastPoint: core.serialization.ObjectSchema<serializers.ForecastPoint.Raw, Chronocast.ForecastPoint> =
    core.serialization.object({
        timestamp: core.serialization.date(),
        value: core.serialization.number(),
        confidenceIntervals: core.serialization.property(
            "confidence_intervals",
            core.serialization.list(ConfidenceInterval).optional(),
        ),
    });

export declare namespace ForecastPoint {
    export interface Raw {
        timestamp: string;
        value: number;
        confidence_intervals?: ConfidenceInterval.Raw[] | null;
    }
}
