// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { ForecastModelStatus } from "./ForecastModelStatus.js";
import { Hyperparameters } from "./Hyperparameters.js";
import { TrainingMetrics } from "./TrainingMetrics.js";

export const ForecastModel: core.serialization.ObjectSchema<serializers.ForecastModel.Raw, Chronocast.ForecastModel> =
    core.serialization.object({
        id: core.serialization.string(),
        projectId: core.serialization.property("project_id", core.serialization.string()),
        name: core.serialization.string(),
        algorithm: core.serialization.lazy(() => serializers.Algorithm),
        status: ForecastModelStatus,
        datasetId: core.serialization.property("dataset_id", core.serialization.string()),
        targetColumn: core.serialization.property("target_column", core.serialization.string()),
        featureColumns: core.serialization.property(
            "feature_columns",
            core.serialization.list(core.serialization.string()),
        ),
        hyperparameters: Hyperparameters.optional(),
        metrics: TrainingMetrics.optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        trainedAt: core.serialization.property("trained_at", core.serialization.date().optional()),
    });

export declare namespace ForecastModel {
    export interface Raw {
        id: string;
        project_id: string;
        name: string;
        algorithm: serializers.Algorithm.Raw;
        status: ForecastModelStatus.Raw;
        dataset_id: string;
        target_column: string;
        feature_columns: string[];
        hyperparameters?: Hyperparameters.Raw | null;
        metrics?: TrainingMetrics.Raw | null;
        created_at: string;
        trained_at?: string | null;
    }
}
