// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ForecastModelStatus: core.serialization.Schema<
    serializers.ForecastModelStatus.Raw,
    Chronocast.ForecastModelStatus
> = core.serialization.enum_(["draft", "training", "trained", "failed", "archived"]);

export declare namespace ForecastModelStatus {
    export type Raw = "draft" | "training" | "trained" | "failed" | "archived";
}
