// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Hyperparameters: core.serialization.ObjectSchema<
    serializers.Hyperparameters.Raw,
    Chronocast.Hyperparameters
> = core.serialization.object({
    learningRate: core.serialization.property("learning_rate", core.serialization.number().optional()),
    epochs: core.serialization.number().optional(),
    batchSize: core.serialization.property("batch_size", core.serialization.number().optional()),
    earlyStopping: core.serialization.property("early_stopping", core.serialization.boolean().optional()),
});

export declare namespace Hyperparameters {
    export interface Raw {
        learning_rate?: number | null;
        epochs?: number | null;
        batch_size?: number | null;
        early_stopping?: boolean | null;
    }
}
