// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MemberRole } from "./MemberRole.js";

export const Member: core.serialization.ObjectSchema<serializers.Member.Raw, Chronocast.Member> =
    core.serialization.object({
        id: core.serialization.string(),
        orgId: core.serialization.property("org_id", core.serialization.string()),
        email: core.serialization.string(),
        role: MemberRole,
        joinedAt: core.serialization.property("joined_at", core.serialization.date()),
    });

export declare namespace Member {
    export interface Raw {
        id: string;
        org_id: string;
        email: string;
        role: MemberRole.Raw;
        joined_at: string;
    }
}
