// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const NeuralAlgorithmArchitecture: core.serialization.Schema<
    serializers.NeuralAlgorithmArchitecture.Raw,
    Chronocast.NeuralAlgorithmArchitecture
> = core.serialization.enum_(["lstm", "transformer", "tcn"]);

export declare namespace NeuralAlgorithmArchitecture {
    export type Raw = "lstm" | "transformer" | "tcn";
}
