// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { NeuralAlgorithmArchitecture } from "./NeuralAlgorithmArchitecture.js";

export const NeuralAlgorithm: core.serialization.ObjectSchema<
    serializers.NeuralAlgorithm.Raw,
    Chronocast.NeuralAlgorithm
> = core.serialization.object({
    architecture: NeuralAlgorithmArchitecture,
    layers: core.serialization.number(),
    hiddenSize: core.serialization.property("hidden_size", core.serialization.number()),
    dropout: core.serialization.number().optional(),
});

export declare namespace NeuralAlgorithm {
    export interface Raw {
        architecture: NeuralAlgorithmArchitecture.Raw;
        layers: number;
        hidden_size: number;
        dropout?: number | null;
    }
}
