// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EmailChannel } from "./EmailChannel.js";
import { SlackChannel } from "./SlackChannel.js";
import { WebhookChannel } from "./WebhookChannel.js";

export const NotificationChannel: core.serialization.Schema<
    serializers.NotificationChannel.Raw,
    Chronocast.NotificationChannel
> = core.serialization
    .union("type", {
        email: EmailChannel,
        slack: SlackChannel,
        webhook: WebhookChannel,
    })
    .transform<Chronocast.NotificationChannel>({
        transform: (value) => {
            switch (value.type) {
                case "email":
                    return Chronocast.NotificationChannel.email(value);
                case "slack":
                    return Chronocast.NotificationChannel.slack(value);
                case "webhook":
                    return Chronocast.NotificationChannel.webhook(value);
                default:
                    return value as Chronocast.NotificationChannel;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace NotificationChannel {
    export type Raw = NotificationChannel.Email | NotificationChannel.Slack | NotificationChannel.Webhook;

    export interface Email extends EmailChannel.Raw {
        type: "email";
    }

    export interface Slack extends SlackChannel.Raw {
        type: "slack";
    }

    export interface Webhook extends WebhookChannel.Raw {
        type: "webhook";
    }
}
