// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, Chronocast.OauthScope> =
    core.serialization.enum_(["read", "write", "admin"]);

export declare namespace OauthScope {
    export type Raw = "read" | "write" | "admin";
}
