// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OffsetPage: core.serialization.ObjectSchema<serializers.OffsetPage.Raw, Chronocast.OffsetPage> =
    core.serialization.object({
        total: core.serialization.number(),
        offset: core.serialization.number(),
        limit: core.serialization.number(),
        data: core.serialization.list(core.serialization.unknown()),
    });

export declare namespace OffsetPage {
    export interface Raw {
        total: number;
        offset: number;
        limit: number;
        data: unknown[];
    }
}
