// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OrganizationPlan: core.serialization.Schema<
    serializers.OrganizationPlan.Raw,
    Chronocast.OrganizationPlan
> = core.serialization.enum_(["free", "pro", "enterprise"]);

export declare namespace OrganizationPlan {
    export type Raw = "free" | "pro" | "enterprise";
}
