// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrganizationPlan } from "./OrganizationPlan.js";

export const Organization: core.serialization.ObjectSchema<serializers.Organization.Raw, Chronocast.Organization> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        slug: core.serialization.string(),
        plan: OrganizationPlan,
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        metadata: core.serialization
            .record(core.serialization.string(), core.serialization.string().optional())
            .optional(),
    });

export declare namespace Organization {
    export interface Raw {
        id: string;
        name: string;
        slug: string;
        plan: OrganizationPlan.Raw;
        created_at: string;
        metadata?: Record<string, string | null | undefined> | null;
    }
}
