// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PredictionRequest: core.serialization.ObjectSchema<
    serializers.PredictionRequest.Raw,
    Chronocast.PredictionRequest
> = core.serialization.object({
    horizon: core.serialization.number(),
    confidenceIntervals: core.serialization.property(
        "confidence_intervals",
        core.serialization.list(core.serialization.number()).optional(),
    ),
    streaming: core.serialization.boolean().optional(),
    inputOverrides: core.serialization.property(
        "input_overrides",
        core.serialization.record(core.serialization.string(), core.serialization.number().optional()).optional(),
    ),
});

export declare namespace PredictionRequest {
    export interface Raw {
        horizon: number;
        confidence_intervals?: number[] | null;
        streaming?: boolean | null;
        input_overrides?: Record<string, number | null | undefined> | null;
    }
}
