// This file was auto-generated by Fern from our API Definition.

import * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { StreamDoneEvent } from "./StreamDoneEvent.js";
import { StreamErrorEvent } from "./StreamErrorEvent.js";
import { StreamPointEvent } from "./StreamPointEvent.js";
import { StreamProgressEvent } from "./StreamProgressEvent.js";

export const PredictionStreamEvent: core.serialization.Schema<
    serializers.PredictionStreamEvent.Raw,
    Chronocast.PredictionStreamEvent
> = core.serialization
    .union("event", {
        point: StreamPointEvent,
        progress: StreamProgressEvent,
        done: StreamDoneEvent,
        error: StreamErrorEvent,
    })
    .transform<Chronocast.PredictionStreamEvent>({
        transform: (value) => {
            switch (value.event) {
                case "point":
                    return Chronocast.PredictionStreamEvent.point(value);
                case "progress":
                    return Chronocast.PredictionStreamEvent.progress(value);
                case "done":
                    return Chronocast.PredictionStreamEvent.done(value);
                case "error":
                    return Chronocast.PredictionStreamEvent.error(value);
                default:
                    return value as Chronocast.PredictionStreamEvent;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace PredictionStreamEvent {
    export type Raw =
        | PredictionStreamEvent.Point
        | PredictionStreamEvent.Progress
        | PredictionStreamEvent.Done
        | PredictionStreamEvent.Error;

    export interface Point extends StreamPointEvent.Raw {
        event: "point";
    }

    export interface Progress extends StreamProgressEvent.Raw {
        event: "progress";
    }

    export interface Done extends StreamDoneEvent.Raw {
        event: "done";
    }

    export interface Error extends StreamErrorEvent.Raw {
        event: "error";
    }
}
