// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ForecastPoint } from "./ForecastPoint.js";

export const PredictionResult: core.serialization.ObjectSchema<
    serializers.PredictionResult.Raw,
    Chronocast.PredictionResult
> = core.serialization.object({
    id: core.serialization.string(),
    modelId: core.serialization.property("model_id", core.serialization.string()),
    horizon: core.serialization.number(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    points: core.serialization.list(ForecastPoint),
});

export declare namespace PredictionResult {
    export interface Raw {
        id: string;
        model_id: string;
        horizon: number;
        created_at: string;
        points: ForecastPoint.Raw[];
    }
}
