// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Project: core.serialization.ObjectSchema<serializers.Project.Raw, Chronocast.Project> =
    core.serialization.object({
        id: core.serialization.string(),
        orgId: core.serialization.property("org_id", core.serialization.string()),
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace Project {
    export interface Raw {
        id: string;
        org_id: string;
        name: string;
        description?: string | null;
        created_at: string;
        updated_at: string;
    }
}
