// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SlackChannel: core.serialization.ObjectSchema<serializers.SlackChannel.Raw, Chronocast.SlackChannel> =
    core.serialization.object({
        channelId: core.serialization.property("channel_id", core.serialization.string()),
        webhookUrl: core.serialization.property("webhook_url", core.serialization.string()),
    });

export declare namespace SlackChannel {
    export interface Raw {
        channel_id: string;
        webhook_url: string;
    }
}
