// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const StreamDoneEvent: core.serialization.ObjectSchema<
    serializers.StreamDoneEvent.Raw,
    Chronocast.StreamDoneEvent
> = core.serialization.object({
    predictionId: core.serialization.property("prediction_id", core.serialization.string()),
});

export declare namespace StreamDoneEvent {
    export interface Raw {
        prediction_id: string;
    }
}
