// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const StreamProgressEvent: core.serialization.ObjectSchema<
    serializers.StreamProgressEvent.Raw,
    Chronocast.StreamProgressEvent
> = core.serialization.object({
    pct: core.serialization.number(),
});

export declare namespace StreamProgressEvent {
    export interface Raw {
        pct: number;
    }
}
