// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ForecastPoint } from "./ForecastPoint.js";

export const StreamPointEvent: core.serialization.ObjectSchema<
    serializers.StreamPointEvent.Raw,
    Chronocast.StreamPointEvent
> = core.serialization.object({
    data: ForecastPoint,
});

export declare namespace StreamPointEvent {
    export interface Raw {
        data: ForecastPoint.Raw;
    }
}
