// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const StreamErrorEvent: core.serialization.ObjectSchema<
    serializers.StreamErrorEvent.Raw,
    Chronocast.StreamErrorEvent
> = core.serialization.object({
    code: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace StreamErrorEvent {
    export interface Raw {
        code: string;
        message: string;
    }
}
