// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ThresholdConditionOperator: core.serialization.Schema<
    serializers.ThresholdConditionOperator.Raw,
    Chronocast.ThresholdConditionOperator
> = core.serialization.enum_(["gt", "gte", "lt", "lte", "eq"]);

export declare namespace ThresholdConditionOperator {
    export type Raw = "gt" | "gte" | "lt" | "lte" | "eq";
}
