// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ThresholdConditionOperator } from "./ThresholdConditionOperator.js";

export const ThresholdCondition: core.serialization.ObjectSchema<
    serializers.ThresholdCondition.Raw,
    Chronocast.ThresholdCondition
> = core.serialization.object({
    metric: core.serialization.string(),
    operator: ThresholdConditionOperator,
    value: core.serialization.number(),
    durationMinutes: core.serialization.property("duration_minutes", core.serialization.number()),
});

export declare namespace ThresholdCondition {
    export interface Raw {
        metric: string;
        operator: ThresholdConditionOperator.Raw;
        value: number;
        duration_minutes: number;
    }
}
