// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TrainingMetrics: core.serialization.ObjectSchema<
    serializers.TrainingMetrics.Raw,
    Chronocast.TrainingMetrics
> = core.serialization.object({
    mae: core.serialization.number(),
    rmse: core.serialization.number(),
    mape: core.serialization.number(),
    rSquared: core.serialization.property("r_squared", core.serialization.number()),
    trainingDurationSeconds: core.serialization.property("training_duration_seconds", core.serialization.number()),
});

export declare namespace TrainingMetrics {
    export interface Raw {
        mae: number;
        rmse: number;
        mape: number;
        r_squared: number;
        training_duration_seconds: number;
    }
}
