// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TrendConditionDirection: core.serialization.Schema<
    serializers.TrendConditionDirection.Raw,
    Chronocast.TrendConditionDirection
> = core.serialization.enum_(["increasing", "decreasing", "either"]);

export declare namespace TrendConditionDirection {
    export type Raw = "increasing" | "decreasing" | "either";
}
