// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TrendConditionDirection } from "./TrendConditionDirection.js";

export const TrendCondition: core.serialization.ObjectSchema<
    serializers.TrendCondition.Raw,
    Chronocast.TrendCondition
> = core.serialization.object({
    direction: TrendConditionDirection,
    slopeThreshold: core.serialization.property("slope_threshold", core.serialization.number()),
    windowSize: core.serialization.property("window_size", core.serialization.number()),
});

export declare namespace TrendCondition {
    export interface Raw {
        direction: TrendConditionDirection.Raw;
        slope_threshold: number;
        window_size: number;
    }
}
