// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookDelivery: core.serialization.ObjectSchema<
    serializers.WebhookDelivery.Raw,
    Chronocast.WebhookDelivery
> = core.serialization.object({
    id: core.serialization.string(),
    webhookId: core.serialization.property("webhook_id", core.serialization.string()),
    eventType: core.serialization.property("event_type", core.serialization.string()),
    payload: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    responseStatus: core.serialization.property("response_status", core.serialization.number().optional()),
    deliveredAt: core.serialization.property("delivered_at", core.serialization.date()),
    success: core.serialization.boolean(),
});

export declare namespace WebhookDelivery {
    export interface Raw {
        id: string;
        webhook_id: string;
        event_type: string;
        payload: Record<string, unknown>;
        response_status?: number | null;
        delivered_at: string;
        success: boolean;
    }
}
