// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookChannel: core.serialization.ObjectSchema<
    serializers.WebhookChannel.Raw,
    Chronocast.WebhookChannel
> = core.serialization.object({
    url: core.serialization.string(),
    secret: core.serialization.string().optional(),
});

export declare namespace WebhookChannel {
    export interface Raw {
        url: string;
        secret?: string | null;
    }
}
