// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookIngestSource: core.serialization.ObjectSchema<
    serializers.WebhookIngestSource.Raw,
    Chronocast.WebhookIngestSource
> = core.serialization.object({
    endpointUrl: core.serialization.property("endpoint_url", core.serialization.string()),
    secret: core.serialization.string(),
});

export declare namespace WebhookIngestSource {
    export interface Raw {
        endpoint_url: string;
        secret: string;
    }
}
