// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { WebhookEndpointEventsItem } from "./WebhookEndpointEventsItem.js";

export const WebhookEndpoint: core.serialization.ObjectSchema<
    serializers.WebhookEndpoint.Raw,
    Chronocast.WebhookEndpoint
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    events: core.serialization.list(WebhookEndpointEventsItem),
    secret: core.serialization.string().optional(),
    active: core.serialization.boolean(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace WebhookEndpoint {
    export interface Raw {
        id: string;
        url: string;
        events: WebhookEndpointEventsItem.Raw[];
        secret?: string | null;
        active: boolean;
        created_at: string;
    }
}
