// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Project } from "../../../types/Project.js";

export const ListProjectsResponse: core.serialization.ObjectSchema<
    serializers.ListProjectsResponse.Raw,
    Chronocast.ListProjectsResponse
> = core.serialization.object({
    data: core.serialization.list(Project).optional(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace ListProjectsResponse {
    export interface Raw {
        data?: Project.Raw[] | null;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
