// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Chronocast from "../../../index.js";

export declare namespace ProjectsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage projects within organizations
 */
export class ProjectsClient {
    protected readonly _options: NormalizedClientOptions<ProjectsClient.Options>;

    constructor(options: ProjectsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {string} org_id
     * @param {Chronocast.ListProjectsRequest} request
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.projects.listProjects("org_id", {
     *         cursor: "cursor",
     *         limit: 1
     *     })
     */
    public listProjects(
        org_id: string,
        request: Chronocast.ListProjectsRequest = {},
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ListProjectsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listProjects(org_id, request, requestOptions));
    }

    private async __listProjects(
        org_id: string,
        request: Chronocast.ListProjectsRequest = {},
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ListProjectsResponse>> {
        const { cursor, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListProjectsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {Chronocast.ProjectCreate} request
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.projects.createProject("org_id", {
     *         idempotencyKey: "Idempotency-Key",
     *         name: "name"
     *     })
     */
    public createProject(
        org_id: string,
        request: Chronocast.ProjectCreate,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Project> {
        return core.HttpResponsePromise.fromPromise(this.__createProject(org_id, request, requestOptions));
    }

    private async __createProject(
        org_id: string,
        request: Chronocast.ProjectCreate,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Project>> {
        const { idempotencyKey, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.ProjectCreate.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Project.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling POST /organizations/{org_id}/projects.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.NotFoundError}
     *
     * @example
     *     await client.projects.getProject("org_id", "project_id")
     */
    public getProject(
        org_id: string,
        project_id: string,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Project> {
        return core.HttpResponsePromise.fromPromise(this.__getProject(org_id, project_id, requestOptions));
    }

    private async __getProject(
        org_id: string,
        project_id: string,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Project>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Project.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Chronocast.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/projects/{project_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {string} project_id
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.projects.deleteProject("org_id", "project_id")
     */
    public deleteProject(
        org_id: string,
        project_id: string,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteProject(org_id, project_id, requestOptions));
    }

    private async __deleteProject(
        org_id: string,
        project_id: string,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/projects/${core.url.encodePathParam(project_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling DELETE /organizations/{org_id}/projects/{project_id}.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
