/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the openapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx organizationsListOrganizations.example.ts
 */

import { SDK } from "openapi";

const sdk = new SDK({
  apiKey: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await sdk.organizations.listOrganizations({});

  console.log(result);
}

main().catch(console.error);
