// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import * as serializers from "../../../../index.js";
import { Hyperparameters } from "../../../../types/Hyperparameters.js";

export const ModelCreate: core.serialization.Schema<
    serializers.ModelCreate.Raw,
    Omit<Chronocast.ModelCreate, "idempotencyKey">
> = core.serialization.object({
    name: core.serialization.string(),
    algorithm: core.serialization.lazy(() => serializers.Algorithm),
    datasetId: core.serialization.property("dataset_id", core.serialization.string()),
    targetColumn: core.serialization.property("target_column", core.serialization.string()),
    featureColumns: core.serialization.property(
        "feature_columns",
        core.serialization.list(core.serialization.string()),
    ),
    hyperparameters: Hyperparameters.optional(),
});

export declare namespace ModelCreate {
    export interface Raw {
        name: string;
        algorithm: serializers.Algorithm.Raw;
        dataset_id: string;
        target_column: string;
        feature_columns: string[];
        hyperparameters?: Hyperparameters.Raw | null;
    }
}
