// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Hyperparameters } from "../../../../types/Hyperparameters.js";

export const TrainModelRequest: core.serialization.Schema<
    serializers.TrainModelRequest.Raw,
    Omit<Chronocast.TrainModelRequest, "idempotencyKey">
> = core.serialization.object({
    hyperparameters: Hyperparameters.optional(),
});

export declare namespace TrainModelRequest {
    export interface Raw {
        hyperparameters?: Hyperparameters.Raw | null;
    }
}
