// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { MemberInviteRole } from "../../types/MemberInviteRole.js";

export const MemberInvite: core.serialization.Schema<
    serializers.MemberInvite.Raw,
    Omit<Chronocast.MemberInvite, "idempotencyKey">
> = core.serialization.object({
    email: core.serialization.string(),
    role: MemberInviteRole.optional(),
});

export declare namespace MemberInvite {
    export interface Raw {
        email: string;
        role?: MemberInviteRole.Raw | null;
    }
}
