// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../index.js";

export interface ListModelsResponse {
    data?: Chronocast.ForecastModel[];
    hasMore: boolean;
    nextCursor?: string;
}
