// This file was auto-generated by Fern from our API Definition.

export const ListModelsRequestStatus = {
    Draft: "draft",
    Training: "training",
    Trained: "trained",
    Failed: "failed",
    Archived: "archived",
    _visit: <R>(value: ListModelsRequestStatus, visitor: ListModelsRequestStatus.Visitor<R>) => {
        switch (value) {
            case ListModelsRequestStatus.Draft:
                return visitor.draft();
            case ListModelsRequestStatus.Training:
                return visitor.training();
            case ListModelsRequestStatus.Trained:
                return visitor.trained();
            case ListModelsRequestStatus.Failed:
                return visitor.failed();
            case ListModelsRequestStatus.Archived:
                return visitor.archived();
            default:
                return visitor._other();
        }
    },
} as const;
export type ListModelsRequestStatus = Omit<typeof ListModelsRequestStatus, "_visit">[keyof Omit<
    typeof ListModelsRequestStatus,
    "_visit"
>];

export namespace ListModelsRequestStatus {
    export interface Visitor<R> {
        draft: () => R;
        training: () => R;
        trained: () => R;
        failed: () => R;
        archived: () => R;
        _other: () => R;
    }
}
