// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../index.js";

export interface ListWebhooksResponse {
    data?: Chronocast.WebhookEndpoint[];
    hasMore: boolean;
    nextCursor?: string;
}
