// This file was auto-generated by Fern from our API Definition.

export const WebhookEndpointCreateEventsItem = {
    ModelTrainingStarted: "model.training.started",
    ModelTrainingCompleted: "model.training.completed",
    ModelTrainingFailed: "model.training.failed",
    PredictionCompleted: "prediction.completed",
    AlertTriggered: "alert.triggered",
    AlertResolved: "alert.resolved",
    DatasetReady: "dataset.ready",
    DatasetFailed: "dataset.failed",
    _visit: <R>(value: WebhookEndpointCreateEventsItem, visitor: WebhookEndpointCreateEventsItem.Visitor<R>) => {
        switch (value) {
            case WebhookEndpointCreateEventsItem.ModelTrainingStarted:
                return visitor.modelTrainingStarted();
            case WebhookEndpointCreateEventsItem.ModelTrainingCompleted:
                return visitor.modelTrainingCompleted();
            case WebhookEndpointCreateEventsItem.ModelTrainingFailed:
                return visitor.modelTrainingFailed();
            case WebhookEndpointCreateEventsItem.PredictionCompleted:
                return visitor.predictionCompleted();
            case WebhookEndpointCreateEventsItem.AlertTriggered:
                return visitor.alertTriggered();
            case WebhookEndpointCreateEventsItem.AlertResolved:
                return visitor.alertResolved();
            case WebhookEndpointCreateEventsItem.DatasetReady:
                return visitor.datasetReady();
            case WebhookEndpointCreateEventsItem.DatasetFailed:
                return visitor.datasetFailed();
            default:
                return visitor._other();
        }
    },
} as const;
export type WebhookEndpointCreateEventsItem = Omit<typeof WebhookEndpointCreateEventsItem, "_visit">[keyof Omit<
    typeof WebhookEndpointCreateEventsItem,
    "_visit"
>];

export namespace WebhookEndpointCreateEventsItem {
    export interface Visitor<R> {
        modelTrainingStarted: () => R;
        modelTrainingCompleted: () => R;
        modelTrainingFailed: () => R;
        predictionCompleted: () => R;
        alertTriggered: () => R;
        alertResolved: () => R;
        datasetReady: () => R;
        datasetFailed: () => R;
        _other: () => R;
    }
}
