/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { SDKError } from "./sdk-error.js";

/**
 * Missing or invalid authentication
 */
export type ApiErrorData = {
  type: models.Type;
  message: string;
  requestId: string;
  details?: Array<models.FieldError> | null | undefined;
};

/**
 * Missing or invalid authentication
 */
export class ApiError extends SDKError {
  type: models.Type;
  requestId: string;
  details?: Array<models.FieldError> | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorData;

  constructor(
    err: ApiErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.requestId = err.requestId;
    if (err.details != null) this.details = err.details;

    this.name = "ApiError";
  }
}

/** @internal */
export const ApiError$inboundSchema: z.ZodMiniType<ApiError, unknown> = z.pipe(
  z.object({
    type: models.Type$inboundSchema,
    message: types.string(),
    request_id: types.string(),
    details: z.optional(z.nullable(z.array(models.FieldError$inboundSchema))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "request_id": "requestId",
    });

    return new ApiError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
