/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AlertCondition,
  AlertCondition$inboundSchema,
} from "./alert-condition.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AlertEvent = {
  id: string;
  alertId: string;
  triggeredAt: Date;
  conditionSnapshot: AlertCondition;
  observedValue: number;
  resolvedAt?: Date | null | undefined;
};

/** @internal */
export const AlertEvent$inboundSchema: z.ZodMiniType<AlertEvent, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      alert_id: types.string(),
      triggered_at: types.date(),
      condition_snapshot: AlertCondition$inboundSchema,
      observed_value: types.number(),
      resolved_at: z.optional(z.nullable(types.date())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "alert_id": "alertId",
        "triggered_at": "triggeredAt",
        "condition_snapshot": "conditionSnapshot",
        "observed_value": "observedValue",
        "resolved_at": "resolvedAt",
      });
    }),
  );

export function alertEventFromJSON(
  jsonString: string,
): SafeParseResult<AlertEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AlertEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AlertEvent' from JSON`,
  );
}
