/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AlertCondition,
  AlertCondition$inboundSchema,
} from "./alert-condition.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  NotificationChannel,
  NotificationChannel$inboundSchema,
} from "./notification-channel.js";

export type Alert = {
  id: string;
  projectId: string;
  name: string;
  modelId: string;
  condition: AlertCondition;
  channels: Array<NotificationChannel>;
  enabled: boolean;
  createdAt: Date;
};

/** @internal */
export const Alert$inboundSchema: z.ZodMiniType<Alert, unknown> = z.pipe(
  z.object({
    id: types.string(),
    project_id: types.string(),
    name: types.string(),
    model_id: types.string(),
    condition: AlertCondition$inboundSchema,
    channels: z.array(NotificationChannel$inboundSchema),
    enabled: types.boolean(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "project_id": "projectId",
      "model_id": "modelId",
      "created_at": "createdAt",
    });
  }),
);

export function alertFromJSON(
  jsonString: string,
): SafeParseResult<Alert, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Alert$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Alert' from JSON`,
  );
}
