/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnomalyCondition,
  AnomalyCondition$inboundSchema,
  AnomalyCondition$Outbound,
  AnomalyCondition$outboundSchema,
} from "./anomaly-condition.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ThresholdCondition,
  ThresholdCondition$inboundSchema,
  ThresholdCondition$Outbound,
  ThresholdCondition$outboundSchema,
} from "./threshold-condition.js";
import {
  TrendCondition,
  TrendCondition$inboundSchema,
  TrendCondition$Outbound,
  TrendCondition$outboundSchema,
} from "./trend-condition.js";

export type AlertCondition =
  | ThresholdCondition
  | AnomalyCondition
  | TrendCondition
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const AlertCondition$inboundSchema: z.ZodMiniType<
  AlertCondition,
  unknown
> = discriminatedUnion("type", {
  threshold: ThresholdCondition$inboundSchema,
  anomaly: AnomalyCondition$inboundSchema,
  trend: TrendCondition$inboundSchema,
});
/** @internal */
export type AlertCondition$Outbound =
  | ThresholdCondition$Outbound
  | AnomalyCondition$Outbound
  | TrendCondition$Outbound;

/** @internal */
export const AlertCondition$outboundSchema: z.ZodMiniType<
  AlertCondition$Outbound,
  AlertCondition
> = z.union([
  ThresholdCondition$outboundSchema,
  AnomalyCondition$outboundSchema,
  TrendCondition$outboundSchema,
]);

export function alertConditionToJSON(alertCondition: AlertCondition): string {
  return JSON.stringify(AlertCondition$outboundSchema.parse(alertCondition));
}
export function alertConditionFromJSON(
  jsonString: string,
): SafeParseResult<AlertCondition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AlertCondition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AlertCondition' from JSON`,
  );
}
