/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AlertCondition,
  AlertCondition$Outbound,
  AlertCondition$outboundSchema,
} from "./alert-condition.js";
import {
  NotificationChannel,
  NotificationChannel$Outbound,
  NotificationChannel$outboundSchema,
} from "./notification-channel.js";

export type AlertCreate = {
  name: string;
  modelId: string;
  condition: AlertCondition;
  channels: Array<NotificationChannel>;
  enabled?: boolean | undefined;
};

/** @internal */
export type AlertCreate$Outbound = {
  name: string;
  model_id: string;
  condition: AlertCondition$Outbound;
  channels: Array<NotificationChannel$Outbound>;
  enabled: boolean;
};

/** @internal */
export const AlertCreate$outboundSchema: z.ZodMiniType<
  AlertCreate$Outbound,
  AlertCreate
> = z.pipe(
  z.object({
    name: z.string(),
    modelId: z.string(),
    condition: AlertCondition$outboundSchema,
    channels: z.array(NotificationChannel$outboundSchema),
    enabled: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
    });
  }),
);

export function alertCreateToJSON(alertCreate: AlertCreate): string {
  return JSON.stringify(AlertCreate$outboundSchema.parse(alertCreate));
}
