/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ArimaAlgorithm,
  ArimaAlgorithm$inboundSchema,
  ArimaAlgorithm$Outbound,
  ArimaAlgorithm$outboundSchema,
} from "./arima-algorithm.js";
import {
  EnsembleAlgorithm1,
  EnsembleAlgorithm1$inboundSchema,
  EnsembleAlgorithm1$Outbound,
  EnsembleAlgorithm1$outboundSchema,
} from "./ensemble-algorithm-1.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  NeuralAlgorithm,
  NeuralAlgorithm$inboundSchema,
  NeuralAlgorithm$Outbound,
  NeuralAlgorithm$outboundSchema,
} from "./neural-algorithm.js";

export type Algorithm =
  | ArimaAlgorithm
  | NeuralAlgorithm
  | EnsembleAlgorithm1
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const Algorithm$inboundSchema: z.ZodMiniType<Algorithm, unknown> =
  discriminatedUnion("type", {
    arima: ArimaAlgorithm$inboundSchema,
    neural: NeuralAlgorithm$inboundSchema,
    ensemble: z.lazy(() => EnsembleAlgorithm1$inboundSchema),
  });
/** @internal */
export type Algorithm$Outbound =
  | ArimaAlgorithm$Outbound
  | NeuralAlgorithm$Outbound
  | EnsembleAlgorithm1$Outbound;

/** @internal */
export const Algorithm$outboundSchema: z.ZodMiniType<
  Algorithm$Outbound,
  Algorithm
> = z.union([
  ArimaAlgorithm$outboundSchema,
  NeuralAlgorithm$outboundSchema,
  z.lazy(() => EnsembleAlgorithm1$outboundSchema),
]);

export function algorithmToJSON(algorithm: Algorithm): string {
  return JSON.stringify(Algorithm$outboundSchema.parse(algorithm));
}
export function algorithmFromJSON(
  jsonString: string,
): SafeParseResult<Algorithm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Algorithm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Algorithm' from JSON`,
  );
}
