/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AnomalyCondition = {
  type: "anomaly";
  /**
   * 0 = least sensitive, 1 = most sensitive
   */
  sensitivity: number;
  minDeviationPct?: number | undefined;
};

/** @internal */
export const AnomalyCondition$inboundSchema: z.ZodMiniType<
  AnomalyCondition,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("anomaly"),
    sensitivity: types.number(),
    min_deviation_pct: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "min_deviation_pct": "minDeviationPct",
    });
  }),
);
/** @internal */
export type AnomalyCondition$Outbound = {
  type: "anomaly";
  sensitivity: number;
  min_deviation_pct?: number | undefined;
};

/** @internal */
export const AnomalyCondition$outboundSchema: z.ZodMiniType<
  AnomalyCondition$Outbound,
  AnomalyCondition
> = z.pipe(
  z.object({
    type: z.literal("anomaly"),
    sensitivity: z.number(),
    minDeviationPct: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      minDeviationPct: "min_deviation_pct",
    });
  }),
);

export function anomalyConditionToJSON(
  anomalyCondition: AnomalyCondition,
): string {
  return JSON.stringify(
    AnomalyCondition$outboundSchema.parse(anomalyCondition),
  );
}
export function anomalyConditionFromJSON(
  jsonString: string,
): SafeParseResult<AnomalyCondition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnomalyCondition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnomalyCondition' from JSON`,
  );
}
