/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const Type = {
  InvalidRequest: "invalid_request",
  AuthenticationError: "authentication_error",
  PermissionDenied: "permission_denied",
  NotFound: "not_found",
  RateLimit: "rate_limit",
  Conflict: "conflict",
  InternalError: "internal_error",
} as const;
export type Type = OpenEnum<typeof Type>;

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);
