/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiPullSource = {
  type: "api_pull";
  sourceUrl: string;
  scheduleCron: string;
  headers?: { [k: string]: string } | undefined;
};

/** @internal */
export const ApiPullSource$inboundSchema: z.ZodMiniType<
  ApiPullSource,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("api_pull"),
    source_url: types.string(),
    schedule_cron: types.string(),
    headers: types.optional(z.record(z.string(), types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_url": "sourceUrl",
      "schedule_cron": "scheduleCron",
    });
  }),
);
/** @internal */
export type ApiPullSource$Outbound = {
  type: "api_pull";
  source_url: string;
  schedule_cron: string;
  headers?: { [k: string]: string } | undefined;
};

/** @internal */
export const ApiPullSource$outboundSchema: z.ZodMiniType<
  ApiPullSource$Outbound,
  ApiPullSource
> = z.pipe(
  z.object({
    type: z.literal("api_pull"),
    sourceUrl: z.string(),
    scheduleCron: z.string(),
    headers: z.optional(z.record(z.string(), z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sourceUrl: "source_url",
      scheduleCron: "schedule_cron",
    });
  }),
);

export function apiPullSourceToJSON(apiPullSource: ApiPullSource): string {
  return JSON.stringify(ApiPullSource$outboundSchema.parse(apiPullSource));
}
export function apiPullSourceFromJSON(
  jsonString: string,
): SafeParseResult<ApiPullSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiPullSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPullSource' from JSON`,
  );
}
