/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ArimaAlgorithm = {
  type: "arima";
  orderP: number;
  orderD: number;
  orderQ: number;
  seasonal?: boolean | undefined;
};

/** @internal */
export const ArimaAlgorithm$inboundSchema: z.ZodMiniType<
  ArimaAlgorithm,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("arima"),
    order_p: types.number(),
    order_d: types.number(),
    order_q: types.number(),
    seasonal: z._default(types.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_p": "orderP",
      "order_d": "orderD",
      "order_q": "orderQ",
    });
  }),
);
/** @internal */
export type ArimaAlgorithm$Outbound = {
  type: "arima";
  order_p: number;
  order_d: number;
  order_q: number;
  seasonal: boolean;
};

/** @internal */
export const ArimaAlgorithm$outboundSchema: z.ZodMiniType<
  ArimaAlgorithm$Outbound,
  ArimaAlgorithm
> = z.pipe(
  z.object({
    type: z.literal("arima"),
    orderP: z.int(),
    orderD: z.int(),
    orderQ: z.int(),
    seasonal: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      orderP: "order_p",
      orderD: "order_d",
      orderQ: "order_q",
    });
  }),
);

export function arimaAlgorithmToJSON(arimaAlgorithm: ArimaAlgorithm): string {
  return JSON.stringify(ArimaAlgorithm$outboundSchema.parse(arimaAlgorithm));
}
export function arimaAlgorithmFromJSON(
  jsonString: string,
): SafeParseResult<ArimaAlgorithm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArimaAlgorithm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArimaAlgorithm' from JSON`,
  );
}
