/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OperationError,
  OperationError$inboundSchema,
} from "./operation-error.js";

export const AsyncOperationStatus = {
  Pending: "pending",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type AsyncOperationStatus = OpenEnum<typeof AsyncOperationStatus>;

export type AsyncOperation = {
  id: string;
  status: AsyncOperationStatus;
  createdAt: Date;
  updatedAt: Date;
  resultUrl?: string | null | undefined;
  error?: OperationError | undefined;
  progressPct?: number | null | undefined;
};

/** @internal */
export const AsyncOperationStatus$inboundSchema: z.ZodMiniType<
  AsyncOperationStatus,
  unknown
> = openEnums.inboundSchema(AsyncOperationStatus);

/** @internal */
export const AsyncOperation$inboundSchema: z.ZodMiniType<
  AsyncOperation,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    status: AsyncOperationStatus$inboundSchema,
    created_at: types.date(),
    updated_at: types.date(),
    result_url: z.optional(z.nullable(types.string())),
    error: types.optional(OperationError$inboundSchema),
    progress_pct: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "result_url": "resultUrl",
      "progress_pct": "progressPct",
    });
  }),
);

export function asyncOperationFromJSON(
  jsonString: string,
): SafeParseResult<AsyncOperation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AsyncOperation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AsyncOperation' from JSON`,
  );
}
