/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type BatchItemError = {
  resultType: "error";
  index: number;
  code: string;
  message: string;
};

/** @internal */
export const BatchItemError$inboundSchema: z.ZodMiniType<
  BatchItemError,
  unknown
> = z.pipe(
  z.object({
    result_type: types.literal("error"),
    index: types.number(),
    code: types.string(),
    message: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "result_type": "resultType",
    });
  }),
);

export function batchItemErrorFromJSON(
  jsonString: string,
): SafeParseResult<BatchItemError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BatchItemError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BatchItemError' from JSON`,
  );
}
