/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Dtype = {
  Float64: "float64",
  Int64: "int64",
  String: "string",
  Datetime: "datetime",
  Boolean: "boolean",
} as const;
export type Dtype = OpenEnum<typeof Dtype>;

export type ColumnSchema = {
  name: string;
  dtype: Dtype;
  nullable: boolean;
};

/** @internal */
export const Dtype$inboundSchema: z.ZodMiniType<Dtype, unknown> = openEnums
  .inboundSchema(Dtype);

/** @internal */
export const ColumnSchema$inboundSchema: z.ZodMiniType<ColumnSchema, unknown> =
  z.object({
    name: types.string(),
    dtype: Dtype$inboundSchema,
    nullable: types.boolean(),
  });

export function columnSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ColumnSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ColumnSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ColumnSchema' from JSON`,
  );
}
