/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ConfidenceInterval = {
  level: number;
  lower: number;
  upper: number;
};

/** @internal */
export const ConfidenceInterval$inboundSchema: z.ZodMiniType<
  ConfidenceInterval,
  unknown
> = z.object({
  level: types.number(),
  lower: types.number(),
  upper: types.number(),
});

export function confidenceIntervalFromJSON(
  jsonString: string,
): SafeParseResult<ConfidenceInterval, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfidenceInterval$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfidenceInterval' from JSON`,
  );
}
