/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ApiPullSource,
  ApiPullSource$inboundSchema,
  ApiPullSource$Outbound,
  ApiPullSource$outboundSchema,
} from "./api-pull-source.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FileUploadSource,
  FileUploadSource$inboundSchema,
  FileUploadSource$Outbound,
  FileUploadSource$outboundSchema,
} from "./file-upload-source.js";
import {
  WebhookIngestSource,
  WebhookIngestSource$inboundSchema,
  WebhookIngestSource$Outbound,
  WebhookIngestSource$outboundSchema,
} from "./webhook-ingest-source.js";

export type DataSource =
  | FileUploadSource
  | WebhookIngestSource
  | ApiPullSource
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const DataSource$inboundSchema: z.ZodMiniType<DataSource, unknown> =
  discriminatedUnion("type", {
    file_upload: FileUploadSource$inboundSchema,
    webhook_ingest: WebhookIngestSource$inboundSchema,
    api_pull: ApiPullSource$inboundSchema,
  });
/** @internal */
export type DataSource$Outbound =
  | FileUploadSource$Outbound
  | WebhookIngestSource$Outbound
  | ApiPullSource$Outbound;

/** @internal */
export const DataSource$outboundSchema: z.ZodMiniType<
  DataSource$Outbound,
  DataSource
> = z.union([
  FileUploadSource$outboundSchema,
  WebhookIngestSource$outboundSchema,
  ApiPullSource$outboundSchema,
]);

export function dataSourceToJSON(dataSource: DataSource): string {
  return JSON.stringify(DataSource$outboundSchema.parse(dataSource));
}
export function dataSourceFromJSON(
  jsonString: string,
): SafeParseResult<DataSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataSource' from JSON`,
  );
}
