/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type EmailChannel = {
  type: "email";
  address: string;
};

/** @internal */
export const EmailChannel$inboundSchema: z.ZodMiniType<EmailChannel, unknown> =
  z.object({
    type: types.literal("email"),
    address: types.string(),
  });
/** @internal */
export type EmailChannel$Outbound = {
  type: "email";
  address: string;
};

/** @internal */
export const EmailChannel$outboundSchema: z.ZodMiniType<
  EmailChannel$Outbound,
  EmailChannel
> = z.object({
  type: z.literal("email"),
  address: z.string(),
});

export function emailChannelToJSON(emailChannel: EmailChannel): string {
  return JSON.stringify(EmailChannel$outboundSchema.parse(emailChannel));
}
export function emailChannelFromJSON(
  jsonString: string,
): SafeParseResult<EmailChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailChannel' from JSON`,
  );
}
