/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Algorithm,
  Algorithm$inboundSchema,
  Algorithm$Outbound,
  Algorithm$outboundSchema,
} from "./algorithm.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const CombinationMethod = {
  Average: "average",
  Weighted: "weighted",
  Stacking: "stacking",
} as const;
export type CombinationMethod = OpenEnum<typeof CombinationMethod>;

export type EnsembleAlgorithm1 = {
  type: "ensemble";
  subAlgorithms: Array<Algorithm>;
  combinationMethod: CombinationMethod;
};

/** @internal */
export const CombinationMethod$inboundSchema: z.ZodMiniType<
  CombinationMethod,
  unknown
> = openEnums.inboundSchema(CombinationMethod);
/** @internal */
export const CombinationMethod$outboundSchema: z.ZodMiniType<
  string,
  CombinationMethod
> = openEnums.outboundSchema(CombinationMethod);

/** @internal */
export const EnsembleAlgorithm1$inboundSchema: z.ZodMiniType<
  EnsembleAlgorithm1,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("ensemble"),
    sub_algorithms: z.array(z.lazy(() => Algorithm$inboundSchema)),
    combination_method: CombinationMethod$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "sub_algorithms": "subAlgorithms",
      "combination_method": "combinationMethod",
    });
  }),
);
/** @internal */
export type EnsembleAlgorithm1$Outbound = {
  type: "ensemble";
  sub_algorithms: Array<Algorithm$Outbound>;
  combination_method: string;
};

/** @internal */
export const EnsembleAlgorithm1$outboundSchema: z.ZodMiniType<
  EnsembleAlgorithm1$Outbound,
  EnsembleAlgorithm1
> = z.pipe(
  z.object({
    type: z.literal("ensemble"),
    subAlgorithms: z.array(z.lazy(() => Algorithm$outboundSchema)),
    combinationMethod: CombinationMethod$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      subAlgorithms: "sub_algorithms",
      combinationMethod: "combination_method",
    });
  }),
);

export function ensembleAlgorithm1ToJSON(
  ensembleAlgorithm1: EnsembleAlgorithm1,
): string {
  return JSON.stringify(
    EnsembleAlgorithm1$outboundSchema.parse(ensembleAlgorithm1),
  );
}
export function ensembleAlgorithm1FromJSON(
  jsonString: string,
): SafeParseResult<EnsembleAlgorithm1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnsembleAlgorithm1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnsembleAlgorithm1' from JSON`,
  );
}
