/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Code = {
  Required: "required",
  InvalidFormat: "invalid_format",
  OutOfRange: "out_of_range",
  TooLong: "too_long",
  TooShort: "too_short",
  UniqueViolation: "unique_violation",
} as const;
export type Code = OpenEnum<typeof Code>;

export type FieldError = {
  field: string;
  message: string;
  code: Code;
};

/** @internal */
export const Code$inboundSchema: z.ZodMiniType<Code, unknown> = openEnums
  .inboundSchema(Code);

/** @internal */
export const FieldError$inboundSchema: z.ZodMiniType<FieldError, unknown> = z
  .object({
    field: types.string(),
    message: types.string(),
    code: Code$inboundSchema,
  });

export function fieldErrorFromJSON(
  jsonString: string,
): SafeParseResult<FieldError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldError' from JSON`,
  );
}
