/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FileUploadSource = {
  type: "file_upload";
  filename: string;
  contentType: string;
};

/** @internal */
export const FileUploadSource$inboundSchema: z.ZodMiniType<
  FileUploadSource,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("file_upload"),
    filename: types.string(),
    content_type: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "content_type": "contentType",
    });
  }),
);
/** @internal */
export type FileUploadSource$Outbound = {
  type: "file_upload";
  filename: string;
  content_type: string;
};

/** @internal */
export const FileUploadSource$outboundSchema: z.ZodMiniType<
  FileUploadSource$Outbound,
  FileUploadSource
> = z.pipe(
  z.object({
    type: z.literal("file_upload"),
    filename: z.string(),
    contentType: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      contentType: "content_type",
    });
  }),
);

export function fileUploadSourceToJSON(
  fileUploadSource: FileUploadSource,
): string {
  return JSON.stringify(
    FileUploadSource$outboundSchema.parse(fileUploadSource),
  );
}
export function fileUploadSourceFromJSON(
  jsonString: string,
): SafeParseResult<FileUploadSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileUploadSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileUploadSource' from JSON`,
  );
}
