/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Algorithm, Algorithm$inboundSchema } from "./algorithm.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  Hyperparameters,
  Hyperparameters$inboundSchema,
} from "./hyperparameters.js";
import {
  TrainingMetrics,
  TrainingMetrics$inboundSchema,
} from "./training-metrics.js";

export const ForecastModelStatus = {
  Draft: "draft",
  Training: "training",
  Trained: "trained",
  Failed: "failed",
  Archived: "archived",
} as const;
export type ForecastModelStatus = OpenEnum<typeof ForecastModelStatus>;

export type ForecastModel = {
  id: string;
  projectId: string;
  name: string;
  algorithm: Algorithm;
  status: ForecastModelStatus;
  datasetId: string;
  targetColumn: string;
  featureColumns: Array<string>;
  hyperparameters?: Hyperparameters | undefined;
  metrics?: TrainingMetrics | undefined;
  createdAt: Date;
  trainedAt?: Date | null | undefined;
};

/** @internal */
export const ForecastModelStatus$inboundSchema: z.ZodMiniType<
  ForecastModelStatus,
  unknown
> = openEnums.inboundSchema(ForecastModelStatus);

/** @internal */
export const ForecastModel$inboundSchema: z.ZodMiniType<
  ForecastModel,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    project_id: types.string(),
    name: types.string(),
    algorithm: Algorithm$inboundSchema,
    status: ForecastModelStatus$inboundSchema,
    dataset_id: types.string(),
    target_column: types.string(),
    feature_columns: z.array(types.string()),
    hyperparameters: types.optional(Hyperparameters$inboundSchema),
    metrics: types.optional(TrainingMetrics$inboundSchema),
    created_at: types.date(),
    trained_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "project_id": "projectId",
      "dataset_id": "datasetId",
      "target_column": "targetColumn",
      "feature_columns": "featureColumns",
      "created_at": "createdAt",
      "trained_at": "trainedAt",
    });
  }),
);

export function forecastModelFromJSON(
  jsonString: string,
): SafeParseResult<ForecastModel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForecastModel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForecastModel' from JSON`,
  );
}
