/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ConfidenceInterval,
  ConfidenceInterval$inboundSchema,
} from "./confidence-interval.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ForecastPoint = {
  timestamp: Date;
  value: number;
  confidenceIntervals?: Array<ConfidenceInterval> | undefined;
};

/** @internal */
export const ForecastPoint$inboundSchema: z.ZodMiniType<
  ForecastPoint,
  unknown
> = z.pipe(
  z.object({
    timestamp: types.date(),
    value: types.number(),
    confidence_intervals: types.optional(
      z.array(ConfidenceInterval$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "confidence_intervals": "confidenceIntervals",
    });
  }),
);

export function forecastPointFromJSON(
  jsonString: string,
): SafeParseResult<ForecastPoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForecastPoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForecastPoint' from JSON`,
  );
}
