/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Hyperparameters = {
  learningRate?: number | undefined;
  epochs?: number | undefined;
  batchSize?: number | undefined;
  earlyStopping?: boolean | undefined;
};

/** @internal */
export const Hyperparameters$inboundSchema: z.ZodMiniType<
  Hyperparameters,
  unknown
> = z.pipe(
  z.object({
    learning_rate: types.optional(types.number()),
    epochs: types.optional(types.number()),
    batch_size: types.optional(types.number()),
    early_stopping: z._default(types.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      "learning_rate": "learningRate",
      "batch_size": "batchSize",
      "early_stopping": "earlyStopping",
    });
  }),
);
/** @internal */
export type Hyperparameters$Outbound = {
  learning_rate?: number | undefined;
  epochs?: number | undefined;
  batch_size?: number | undefined;
  early_stopping: boolean;
};

/** @internal */
export const Hyperparameters$outboundSchema: z.ZodMiniType<
  Hyperparameters$Outbound,
  Hyperparameters
> = z.pipe(
  z.object({
    learningRate: z.optional(z.number()),
    epochs: z.optional(z.int()),
    batchSize: z.optional(z.int()),
    earlyStopping: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      learningRate: "learning_rate",
      batchSize: "batch_size",
      earlyStopping: "early_stopping",
    });
  }),
);

export function hyperparametersToJSON(
  hyperparameters: Hyperparameters,
): string {
  return JSON.stringify(Hyperparameters$outboundSchema.parse(hyperparameters));
}
export function hyperparametersFromJSON(
  jsonString: string,
): SafeParseResult<Hyperparameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Hyperparameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Hyperparameters' from JSON`,
  );
}
