/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MemberRole = {
  Owner: "owner",
  Admin: "admin",
  Member: "member",
  Viewer: "viewer",
} as const;
export type MemberRole = OpenEnum<typeof MemberRole>;

export type Member = {
  id: string;
  orgId: string;
  email: string;
  role: MemberRole;
  joinedAt: Date;
};

/** @internal */
export const MemberRole$inboundSchema: z.ZodMiniType<MemberRole, unknown> =
  openEnums.inboundSchema(MemberRole);

/** @internal */
export const Member$inboundSchema: z.ZodMiniType<Member, unknown> = z.pipe(
  z.object({
    id: types.string(),
    org_id: types.string(),
    email: types.string(),
    role: MemberRole$inboundSchema,
    joined_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "org_id": "orgId",
      "joined_at": "joinedAt",
    });
  }),
);

export function memberFromJSON(
  jsonString: string,
): SafeParseResult<Member, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Member$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Member' from JSON`,
  );
}
