/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const MemberInviteRole = {
  Admin: "admin",
  Member: "member",
  Viewer: "viewer",
} as const;
export type MemberInviteRole = ClosedEnum<typeof MemberInviteRole>;

export type MemberInvite = {
  email: string;
  role?: MemberInviteRole | undefined;
};

/** @internal */
export const MemberInviteRole$outboundSchema: z.ZodMiniEnum<
  typeof MemberInviteRole
> = z.enum(MemberInviteRole);

/** @internal */
export type MemberInvite$Outbound = {
  email: string;
  role: string;
};

/** @internal */
export const MemberInvite$outboundSchema: z.ZodMiniType<
  MemberInvite$Outbound,
  MemberInvite
> = z.object({
  email: z.string(),
  role: z._default(MemberInviteRole$outboundSchema, "member"),
});

export function memberInviteToJSON(memberInvite: MemberInvite): string {
  return JSON.stringify(MemberInvite$outboundSchema.parse(memberInvite));
}
