/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  Algorithm,
  Algorithm$Outbound,
  Algorithm$outboundSchema,
} from "./algorithm.js";
import {
  Hyperparameters,
  Hyperparameters$Outbound,
  Hyperparameters$outboundSchema,
} from "./hyperparameters.js";

export type ModelCreate = {
  name: string;
  algorithm: Algorithm;
  datasetId: string;
  targetColumn: string;
  featureColumns: Array<string>;
  hyperparameters?: Hyperparameters | undefined;
};

/** @internal */
export type ModelCreate$Outbound = {
  name: string;
  algorithm: Algorithm$Outbound;
  dataset_id: string;
  target_column: string;
  feature_columns: Array<string>;
  hyperparameters?: Hyperparameters$Outbound | undefined;
};

/** @internal */
export const ModelCreate$outboundSchema: z.ZodMiniType<
  ModelCreate$Outbound,
  ModelCreate
> = z.pipe(
  z.object({
    name: z.string(),
    algorithm: Algorithm$outboundSchema,
    datasetId: z.string(),
    targetColumn: z.string(),
    featureColumns: z.array(z.string()),
    hyperparameters: z.optional(Hyperparameters$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      targetColumn: "target_column",
      featureColumns: "feature_columns",
    });
  }),
);

export function modelCreateToJSON(modelCreate: ModelCreate): string {
  return JSON.stringify(ModelCreate$outboundSchema.parse(modelCreate));
}
