/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Architecture = {
  Lstm: "lstm",
  Transformer: "transformer",
  Tcn: "tcn",
} as const;
export type Architecture = OpenEnum<typeof Architecture>;

export type NeuralAlgorithm = {
  type: "neural";
  architecture: Architecture;
  layers: number;
  hiddenSize: number;
  dropout?: number | undefined;
};

/** @internal */
export const Architecture$inboundSchema: z.ZodMiniType<Architecture, unknown> =
  openEnums.inboundSchema(Architecture);
/** @internal */
export const Architecture$outboundSchema: z.ZodMiniType<string, Architecture> =
  openEnums.outboundSchema(Architecture);

/** @internal */
export const NeuralAlgorithm$inboundSchema: z.ZodMiniType<
  NeuralAlgorithm,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("neural"),
    architecture: Architecture$inboundSchema,
    layers: types.number(),
    hidden_size: types.number(),
    dropout: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "hidden_size": "hiddenSize",
    });
  }),
);
/** @internal */
export type NeuralAlgorithm$Outbound = {
  type: "neural";
  architecture: string;
  layers: number;
  hidden_size: number;
  dropout?: number | undefined;
};

/** @internal */
export const NeuralAlgorithm$outboundSchema: z.ZodMiniType<
  NeuralAlgorithm$Outbound,
  NeuralAlgorithm
> = z.pipe(
  z.object({
    type: z.literal("neural"),
    architecture: Architecture$outboundSchema,
    layers: z.int(),
    hiddenSize: z.int(),
    dropout: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      hiddenSize: "hidden_size",
    });
  }),
);

export function neuralAlgorithmToJSON(
  neuralAlgorithm: NeuralAlgorithm,
): string {
  return JSON.stringify(NeuralAlgorithm$outboundSchema.parse(neuralAlgorithm));
}
export function neuralAlgorithmFromJSON(
  jsonString: string,
): SafeParseResult<NeuralAlgorithm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NeuralAlgorithm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NeuralAlgorithm' from JSON`,
  );
}
