/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EmailChannel,
  EmailChannel$inboundSchema,
  EmailChannel$Outbound,
  EmailChannel$outboundSchema,
} from "./email-channel.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SlackChannel,
  SlackChannel$inboundSchema,
  SlackChannel$Outbound,
  SlackChannel$outboundSchema,
} from "./slack-channel.js";
import {
  WebhookChannel,
  WebhookChannel$inboundSchema,
  WebhookChannel$Outbound,
  WebhookChannel$outboundSchema,
} from "./webhook-channel.js";

export type NotificationChannel =
  | EmailChannel
  | SlackChannel
  | WebhookChannel
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const NotificationChannel$inboundSchema: z.ZodMiniType<
  NotificationChannel,
  unknown
> = discriminatedUnion("type", {
  email: EmailChannel$inboundSchema,
  slack: SlackChannel$inboundSchema,
  webhook: WebhookChannel$inboundSchema,
});
/** @internal */
export type NotificationChannel$Outbound =
  | EmailChannel$Outbound
  | SlackChannel$Outbound
  | WebhookChannel$Outbound;

/** @internal */
export const NotificationChannel$outboundSchema: z.ZodMiniType<
  NotificationChannel$Outbound,
  NotificationChannel
> = z.union([
  EmailChannel$outboundSchema,
  SlackChannel$outboundSchema,
  WebhookChannel$outboundSchema,
]);

export function notificationChannelToJSON(
  notificationChannel: NotificationChannel,
): string {
  return JSON.stringify(
    NotificationChannel$outboundSchema.parse(notificationChannel),
  );
}
export function notificationChannelFromJSON(
  jsonString: string,
): SafeParseResult<NotificationChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotificationChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotificationChannel' from JSON`,
  );
}
