/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const OrganizationPlan = {
  Free: "free",
  Pro: "pro",
  Enterprise: "enterprise",
} as const;
export type OrganizationPlan = OpenEnum<typeof OrganizationPlan>;

export type Organization = {
  id: string;
  name: string;
  slug: string;
  plan: OrganizationPlan;
  createdAt: Date;
  metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const OrganizationPlan$inboundSchema: z.ZodMiniType<
  OrganizationPlan,
  unknown
> = openEnums.inboundSchema(OrganizationPlan);

/** @internal */
export const Organization$inboundSchema: z.ZodMiniType<Organization, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      slug: types.string(),
      plan: OrganizationPlan$inboundSchema,
      created_at: types.date(),
      metadata: z.optional(z.nullable(z.record(z.string(), types.string()))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
      });
    }),
  );

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
