/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const OrganizationCreatePlan = {
  Free: "free",
  Pro: "pro",
  Enterprise: "enterprise",
} as const;
export type OrganizationCreatePlan = ClosedEnum<typeof OrganizationCreatePlan>;

export type OrganizationCreate = {
  name: string;
  slug: string;
  plan?: OrganizationCreatePlan | undefined;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const OrganizationCreatePlan$outboundSchema: z.ZodMiniEnum<
  typeof OrganizationCreatePlan
> = z.enum(OrganizationCreatePlan);

/** @internal */
export type OrganizationCreate$Outbound = {
  name: string;
  slug: string;
  plan: string;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const OrganizationCreate$outboundSchema: z.ZodMiniType<
  OrganizationCreate$Outbound,
  OrganizationCreate
> = z.object({
  name: z.string(),
  slug: z.string(),
  plan: z._default(OrganizationCreatePlan$outboundSchema, "free"),
  metadata: z.optional(z.record(z.string(), z.string())),
});

export function organizationCreateToJSON(
  organizationCreate: OrganizationCreate,
): string {
  return JSON.stringify(
    OrganizationCreate$outboundSchema.parse(organizationCreate),
  );
}
