/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Project = {
  id: string;
  orgId: string;
  name: string;
  description?: string | null | undefined;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Project$inboundSchema: z.ZodMiniType<Project, unknown> = z.pipe(
  z.object({
    id: types.string(),
    org_id: types.string(),
    name: types.string(),
    description: z.optional(z.nullable(types.string())),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "org_id": "orgId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function projectFromJSON(
  jsonString: string,
): SafeParseResult<Project, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Project$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Project' from JSON`,
  );
}
