/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ProjectCreate = {
  name: string;
  description?: string | null | undefined;
};

/** @internal */
export type ProjectCreate$Outbound = {
  name: string;
  description?: string | null | undefined;
};

/** @internal */
export const ProjectCreate$outboundSchema: z.ZodMiniType<
  ProjectCreate$Outbound,
  ProjectCreate
> = z.object({
  name: z.string(),
  description: z.optional(z.nullable(z.string())),
});

export function projectCreateToJSON(projectCreate: ProjectCreate): string {
  return JSON.stringify(ProjectCreate$outboundSchema.parse(projectCreate));
}
