/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SlackChannel = {
  type: "slack";
  channelId: string;
  webhookUrl: string;
};

/** @internal */
export const SlackChannel$inboundSchema: z.ZodMiniType<SlackChannel, unknown> =
  z.pipe(
    z.object({
      type: types.literal("slack"),
      channel_id: types.string(),
      webhook_url: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "channel_id": "channelId",
        "webhook_url": "webhookUrl",
      });
    }),
  );
/** @internal */
export type SlackChannel$Outbound = {
  type: "slack";
  channel_id: string;
  webhook_url: string;
};

/** @internal */
export const SlackChannel$outboundSchema: z.ZodMiniType<
  SlackChannel$Outbound,
  SlackChannel
> = z.pipe(
  z.object({
    type: z.literal("slack"),
    channelId: z.string(),
    webhookUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      channelId: "channel_id",
      webhookUrl: "webhook_url",
    });
  }),
);

export function slackChannelToJSON(slackChannel: SlackChannel): string {
  return JSON.stringify(SlackChannel$outboundSchema.parse(slackChannel));
}
export function slackChannelFromJSON(
  jsonString: string,
): SafeParseResult<SlackChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlackChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlackChannel' from JSON`,
  );
}
