/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StreamDoneEventData = {
  predictionId: string;
};

export type StreamDoneEvent = {
  event: "done";
  data: StreamDoneEventData;
};

/** @internal */
export const StreamDoneEventData$inboundSchema: z.ZodMiniType<
  StreamDoneEventData,
  unknown
> = z.pipe(
  z.object({
    prediction_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "prediction_id": "predictionId",
    });
  }),
);

export function streamDoneEventDataFromJSON(
  jsonString: string,
): SafeParseResult<StreamDoneEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamDoneEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamDoneEventData' from JSON`,
  );
}

/** @internal */
export const StreamDoneEvent$inboundSchema: z.ZodMiniType<
  StreamDoneEvent,
  unknown
> = z.object({
  event: types.literal("done"),
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    z.lazy(() => StreamDoneEventData$inboundSchema),
  ),
});

export function streamDoneEventFromJSON(
  jsonString: string,
): SafeParseResult<StreamDoneEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamDoneEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamDoneEvent' from JSON`,
  );
}
