/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ForecastPoint,
  ForecastPoint$inboundSchema,
} from "./forecast-point.js";

export type StreamPointEvent = {
  event: "point";
  data: ForecastPoint;
};

/** @internal */
export const StreamPointEvent$inboundSchema: z.ZodMiniType<
  StreamPointEvent,
  unknown
> = z.object({
  event: types.literal("point"),
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    ForecastPoint$inboundSchema,
  ),
});

export function streamPointEventFromJSON(
  jsonString: string,
): SafeParseResult<StreamPointEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamPointEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamPointEvent' from JSON`,
  );
}
