/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StreamErrorEventData = {
  code: string;
  message: string;
};

export type StreamErrorEvent = {
  event: "error";
  data: StreamErrorEventData;
};

/** @internal */
export const StreamErrorEventData$inboundSchema: z.ZodMiniType<
  StreamErrorEventData,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
});

export function streamErrorEventDataFromJSON(
  jsonString: string,
): SafeParseResult<StreamErrorEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamErrorEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamErrorEventData' from JSON`,
  );
}

/** @internal */
export const StreamErrorEvent$inboundSchema: z.ZodMiniType<
  StreamErrorEvent,
  unknown
> = z.object({
  event: types.literal("error"),
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    z.lazy(() => StreamErrorEventData$inboundSchema),
  ),
});

export function streamErrorEventFromJSON(
  jsonString: string,
): SafeParseResult<StreamErrorEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamErrorEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamErrorEvent' from JSON`,
  );
}
