/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StreamProgressEventData = {
  pct: number;
};

export type StreamProgressEvent = {
  event: "progress";
  data: StreamProgressEventData;
};

/** @internal */
export const StreamProgressEventData$inboundSchema: z.ZodMiniType<
  StreamProgressEventData,
  unknown
> = z.object({
  pct: types.number(),
});

export function streamProgressEventDataFromJSON(
  jsonString: string,
): SafeParseResult<StreamProgressEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamProgressEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamProgressEventData' from JSON`,
  );
}

/** @internal */
export const StreamProgressEvent$inboundSchema: z.ZodMiniType<
  StreamProgressEvent,
  unknown
> = z.object({
  event: types.literal("progress"),
  data: z.pipe(
    z.pipe(
      z.string(),
      z.transform((v, ctx) => {
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    z.lazy(() => StreamProgressEventData$inboundSchema),
  ),
});

export function streamProgressEventFromJSON(
  jsonString: string,
): SafeParseResult<StreamProgressEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamProgressEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamProgressEvent' from JSON`,
  );
}
