/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Operator = {
  Gt: "gt",
  Gte: "gte",
  Lt: "lt",
  Lte: "lte",
  Eq: "eq",
} as const;
export type Operator = OpenEnum<typeof Operator>;

export type ThresholdCondition = {
  type: "threshold";
  metric: string;
  operator: Operator;
  value: number;
  durationMinutes: number;
};

/** @internal */
export const Operator$inboundSchema: z.ZodMiniType<Operator, unknown> =
  openEnums.inboundSchema(Operator);
/** @internal */
export const Operator$outboundSchema: z.ZodMiniType<string, Operator> =
  openEnums.outboundSchema(Operator);

/** @internal */
export const ThresholdCondition$inboundSchema: z.ZodMiniType<
  ThresholdCondition,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("threshold"),
    metric: types.string(),
    operator: Operator$inboundSchema,
    value: types.number(),
    duration_minutes: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "duration_minutes": "durationMinutes",
    });
  }),
);
/** @internal */
export type ThresholdCondition$Outbound = {
  type: "threshold";
  metric: string;
  operator: string;
  value: number;
  duration_minutes: number;
};

/** @internal */
export const ThresholdCondition$outboundSchema: z.ZodMiniType<
  ThresholdCondition$Outbound,
  ThresholdCondition
> = z.pipe(
  z.object({
    type: z.literal("threshold"),
    metric: z.string(),
    operator: Operator$outboundSchema,
    value: z.number(),
    durationMinutes: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      durationMinutes: "duration_minutes",
    });
  }),
);

export function thresholdConditionToJSON(
  thresholdCondition: ThresholdCondition,
): string {
  return JSON.stringify(
    ThresholdCondition$outboundSchema.parse(thresholdCondition),
  );
}
export function thresholdConditionFromJSON(
  jsonString: string,
): SafeParseResult<ThresholdCondition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThresholdCondition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThresholdCondition' from JSON`,
  );
}
