/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TrainingMetrics = {
  /**
   * Mean absolute error
   */
  mae: number;
  /**
   * Root mean squared error
   */
  rmse: number;
  /**
   * Mean absolute percentage error
   */
  mape: number;
  rSquared: number;
  trainingDurationSeconds: number;
};

/** @internal */
export const TrainingMetrics$inboundSchema: z.ZodMiniType<
  TrainingMetrics,
  unknown
> = z.pipe(
  z.object({
    mae: types.number(),
    rmse: types.number(),
    mape: types.number(),
    r_squared: types.number(),
    training_duration_seconds: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "r_squared": "rSquared",
      "training_duration_seconds": "trainingDurationSeconds",
    });
  }),
);

export function trainingMetricsFromJSON(
  jsonString: string,
): SafeParseResult<TrainingMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrainingMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrainingMetrics' from JSON`,
  );
}
