/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WebhookIngestSource = {
  type: "webhook_ingest";
  endpointUrl: string;
  secret: string;
};

/** @internal */
export const WebhookIngestSource$inboundSchema: z.ZodMiniType<
  WebhookIngestSource,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("webhook_ingest"),
    endpoint_url: types.string(),
    secret: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "endpoint_url": "endpointUrl",
    });
  }),
);
/** @internal */
export type WebhookIngestSource$Outbound = {
  type: "webhook_ingest";
  endpoint_url: string;
  secret: string;
};

/** @internal */
export const WebhookIngestSource$outboundSchema: z.ZodMiniType<
  WebhookIngestSource$Outbound,
  WebhookIngestSource
> = z.pipe(
  z.object({
    type: z.literal("webhook_ingest"),
    endpointUrl: z.string(),
    secret: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      endpointUrl: "endpoint_url",
    });
  }),
);

export function webhookIngestSourceToJSON(
  webhookIngestSource: WebhookIngestSource,
): string {
  return JSON.stringify(
    WebhookIngestSource$outboundSchema.parse(webhookIngestSource),
  );
}
export function webhookIngestSourceFromJSON(
  jsonString: string,
): SafeParseResult<WebhookIngestSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookIngestSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookIngestSource' from JSON`,
  );
}
