/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const WebhookEndpointCreateEvent = {
  ModelTrainingStarted: "model.training.started",
  ModelTrainingCompleted: "model.training.completed",
  ModelTrainingFailed: "model.training.failed",
  PredictionCompleted: "prediction.completed",
  AlertTriggered: "alert.triggered",
  AlertResolved: "alert.resolved",
  DatasetReady: "dataset.ready",
  DatasetFailed: "dataset.failed",
} as const;
export type WebhookEndpointCreateEvent = ClosedEnum<
  typeof WebhookEndpointCreateEvent
>;

export type WebhookEndpointCreate = {
  url: string;
  events: Array<WebhookEndpointCreateEvent>;
};

/** @internal */
export const WebhookEndpointCreateEvent$outboundSchema: z.ZodMiniEnum<
  typeof WebhookEndpointCreateEvent
> = z.enum(WebhookEndpointCreateEvent);

/** @internal */
export type WebhookEndpointCreate$Outbound = {
  url: string;
  events: Array<string>;
};

/** @internal */
export const WebhookEndpointCreate$outboundSchema: z.ZodMiniType<
  WebhookEndpointCreate$Outbound,
  WebhookEndpointCreate
> = z.object({
  url: z.string(),
  events: z.array(WebhookEndpointCreateEvent$outboundSchema),
});

export function webhookEndpointCreateToJSON(
  webhookEndpointCreate: WebhookEndpointCreate,
): string {
  return JSON.stringify(
    WebhookEndpointCreate$outboundSchema.parse(webhookEndpointCreate),
  );
}
