/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WebhookDelivery = {
  id: string;
  webhookId: string;
  eventType: string;
  payload: { [k: string]: any };
  responseStatus?: number | null | undefined;
  deliveredAt: Date;
  success: boolean;
};

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    webhook_id: types.string(),
    event_type: types.string(),
    payload: z.record(z.string(), z.any()),
    response_status: z.optional(z.nullable(types.number())),
    delivered_at: types.date(),
    success: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "webhook_id": "webhookId",
      "event_type": "eventType",
      "response_status": "responseStatus",
      "delivered_at": "deliveredAt",
    });
  }),
);

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}
