/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WebhookChannel = {
  type: "webhook";
  url: string;
  secret?: string | undefined;
};

/** @internal */
export const WebhookChannel$inboundSchema: z.ZodMiniType<
  WebhookChannel,
  unknown
> = z.object({
  type: types.literal("webhook"),
  url: types.string(),
  secret: types.optional(types.string()),
});
/** @internal */
export type WebhookChannel$Outbound = {
  type: "webhook";
  url: string;
  secret?: string | undefined;
};

/** @internal */
export const WebhookChannel$outboundSchema: z.ZodMiniType<
  WebhookChannel$Outbound,
  WebhookChannel
> = z.object({
  type: z.literal("webhook"),
  url: z.string(),
  secret: z.optional(z.string()),
});

export function webhookChannelToJSON(webhookChannel: WebhookChannel): string {
  return JSON.stringify(WebhookChannel$outboundSchema.parse(webhookChannel));
}
export function webhookChannelFromJSON(
  jsonString: string,
): SafeParseResult<WebhookChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookChannel' from JSON`,
  );
}
