/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookEndpointEvent = {
  ModelTrainingStarted: "model.training.started",
  ModelTrainingCompleted: "model.training.completed",
  ModelTrainingFailed: "model.training.failed",
  PredictionCompleted: "prediction.completed",
  AlertTriggered: "alert.triggered",
  AlertResolved: "alert.resolved",
  DatasetReady: "dataset.ready",
  DatasetFailed: "dataset.failed",
} as const;
export type WebhookEndpointEvent = OpenEnum<typeof WebhookEndpointEvent>;

export type WebhookEndpoint = {
  id: string;
  url: string;
  events: Array<WebhookEndpointEvent>;
  /**
   * HMAC-SHA256 signing secret (only returned on creation)
   */
  secret?: string | undefined;
  active: boolean;
  createdAt: Date;
};

/** @internal */
export const WebhookEndpointEvent$inboundSchema: z.ZodMiniType<
  WebhookEndpointEvent,
  unknown
> = openEnums.inboundSchema(WebhookEndpointEvent);

/** @internal */
export const WebhookEndpoint$inboundSchema: z.ZodMiniType<
  WebhookEndpoint,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    url: types.string(),
    events: z.array(WebhookEndpointEvent$inboundSchema),
    secret: types.optional(types.string()),
    active: types.boolean(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function webhookEndpointFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpoint' from JSON`,
  );
}
