// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../index.js";

export interface ListAlertHistoryResponse {
    data?: Chronocast.AlertEvent[];
    total: number;
    offset: number;
    limit: number;
}
