// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Chronocast from "../../../index.js";

export declare namespace MembersClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage organization members and RBAC
 */
export class MembersClient {
    protected readonly _options: NormalizedClientOptions<MembersClient.Options>;

    constructor(options: MembersClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {string} org_id
     * @param {Chronocast.ListMembersRequest} request
     * @param {MembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.members.listMembers("org_id", {
     *         cursor: "cursor",
     *         limit: 1,
     *         role: "owner"
     *     })
     */
    public listMembers(
        org_id: string,
        request: Chronocast.ListMembersRequest = {},
        requestOptions?: MembersClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.ListMembersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listMembers(org_id, request, requestOptions));
    }

    private async __listMembers(
        org_id: string,
        request: Chronocast.ListMembersRequest = {},
        requestOptions?: MembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.ListMembersResponse>> {
        const { cursor, limit, role } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (role != null) {
            _queryParams.role = serializers.ListMembersRequestRole.jsonOrThrow(role, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            });
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/members`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListMembersResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChronocastError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling GET /organizations/{org_id}/members.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} org_id
     * @param {Chronocast.MemberInvite} request
     * @param {MembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Chronocast.BadRequestError}
     *
     * @example
     *     await client.members.inviteMember("org_id", {
     *         idempotencyKey: "Idempotency-Key",
     *         email: "email"
     *     })
     */
    public inviteMember(
        org_id: string,
        request: Chronocast.MemberInvite,
        requestOptions?: MembersClient.RequestOptions,
    ): core.HttpResponsePromise<Chronocast.Member> {
        return core.HttpResponsePromise.fromPromise(this.__inviteMember(org_id, request, requestOptions));
    }

    private async __inviteMember(
        org_id: string,
        request: Chronocast.MemberInvite,
        requestOptions?: MembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Chronocast.Member>> {
        const { idempotencyKey, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronocastEnvironment.Production,
                `organizations/${core.url.encodePathParam(org_id)}/members`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.MemberInvite.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip", omitUndefined: true }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Member.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Chronocast.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronocastError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.ChronocastError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ChronocastTimeoutError(
                    "Timeout exceeded when calling POST /organizations/{org_id}/members.",
                );
            case "unknown":
                throw new errors.ChronocastError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
