/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CancelOperationRequest = {
  operationId: string;
};

export type CancelOperationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AsyncOperation;
};

/** @internal */
export type CancelOperationRequest$Outbound = {
  operation_id: string;
};

/** @internal */
export const CancelOperationRequest$outboundSchema: z.ZodMiniType<
  CancelOperationRequest$Outbound,
  CancelOperationRequest
> = z.pipe(
  z.object({
    operationId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      operationId: "operation_id",
    });
  }),
);

export function cancelOperationRequestToJSON(
  cancelOperationRequest: CancelOperationRequest,
): string {
  return JSON.stringify(
    CancelOperationRequest$outboundSchema.parse(cancelOperationRequest),
  );
}

/** @internal */
export const CancelOperationResponse$inboundSchema: z.ZodMiniType<
  CancelOperationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.AsyncOperation$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function cancelOperationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelOperationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelOperationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelOperationResponse' from JSON`,
  );
}
