/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateProjectRequest = {
  orgId: string;
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.ProjectCreate;
};

/** @internal */
export type CreateProjectRequest$Outbound = {
  org_id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.ProjectCreate$Outbound;
};

/** @internal */
export const CreateProjectRequest$outboundSchema: z.ZodMiniType<
  CreateProjectRequest$Outbound,
  CreateProjectRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.ProjectCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createProjectRequestToJSON(
  createProjectRequest: CreateProjectRequest,
): string {
  return JSON.stringify(
    CreateProjectRequest$outboundSchema.parse(createProjectRequest),
  );
}
