/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateWebhookSecurity = {
  bearerAuth: string;
};

export type CreateWebhookRequest = {
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.WebhookEndpointCreate;
};

/** @internal */
export type CreateWebhookSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const CreateWebhookSecurity$outboundSchema: z.ZodMiniType<
  CreateWebhookSecurity$Outbound,
  CreateWebhookSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function createWebhookSecurityToJSON(
  createWebhookSecurity: CreateWebhookSecurity,
): string {
  return JSON.stringify(
    CreateWebhookSecurity$outboundSchema.parse(createWebhookSecurity),
  );
}

/** @internal */
export type CreateWebhookRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.WebhookEndpointCreate$Outbound;
};

/** @internal */
export const CreateWebhookRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookRequest$Outbound,
  CreateWebhookRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.WebhookEndpointCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createWebhookRequestToJSON(
  createWebhookRequest: CreateWebhookRequest,
): string {
  return JSON.stringify(
    CreateWebhookRequest$outboundSchema.parse(createWebhookRequest),
  );
}
