/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateModelRequest = {
  orgId: string;
  projectId: string;
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.ModelCreate;
};

export type CreateModelResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ForecastModel;
};

/** @internal */
export type CreateModelRequest$Outbound = {
  org_id: string;
  project_id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.ModelCreate$Outbound;
};

/** @internal */
export const CreateModelRequest$outboundSchema: z.ZodMiniType<
  CreateModelRequest$Outbound,
  CreateModelRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.ModelCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createModelRequestToJSON(
  createModelRequest: CreateModelRequest,
): string {
  return JSON.stringify(
    CreateModelRequest$outboundSchema.parse(createModelRequest),
  );
}

/** @internal */
export const CreateModelResponse$inboundSchema: z.ZodMiniType<
  CreateModelResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ForecastModel$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateModelResponse' from JSON`,
  );
}
