/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateOrganizationRequest = {
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.OrganizationCreate;
};

export type CreateOrganizationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Organization;
};

/** @internal */
export type CreateOrganizationRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.OrganizationCreate$Outbound;
};

/** @internal */
export const CreateOrganizationRequest$outboundSchema: z.ZodMiniType<
  CreateOrganizationRequest$Outbound,
  CreateOrganizationRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.OrganizationCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createOrganizationRequestToJSON(
  createOrganizationRequest: CreateOrganizationRequest,
): string {
  return JSON.stringify(
    CreateOrganizationRequest$outboundSchema.parse(createOrganizationRequest),
  );
}

/** @internal */
export const CreateOrganizationResponse$inboundSchema: z.ZodMiniType<
  CreateOrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Organization$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrganizationResponse' from JSON`,
  );
}
