/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateAlertRequest = {
  orgId: string;
  projectId: string;
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.AlertCreate;
};

/** @internal */
export type CreateAlertRequest$Outbound = {
  org_id: string;
  project_id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.AlertCreate$Outbound;
};

/** @internal */
export const CreateAlertRequest$outboundSchema: z.ZodMiniType<
  CreateAlertRequest$Outbound,
  CreateAlertRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.AlertCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createAlertRequestToJSON(
  createAlertRequest: CreateAlertRequest,
): string {
  return JSON.stringify(
    CreateAlertRequest$outboundSchema.parse(createAlertRequest),
  );
}
