/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteAlertRequest = {
  orgId: string;
  projectId: string;
  alertId: string;
};

/** @internal */
export type DeleteAlertRequest$Outbound = {
  org_id: string;
  project_id: string;
  alert_id: string;
};

/** @internal */
export const DeleteAlertRequest$outboundSchema: z.ZodMiniType<
  DeleteAlertRequest$Outbound,
  DeleteAlertRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    alertId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      alertId: "alert_id",
    });
  }),
);

export function deleteAlertRequestToJSON(
  deleteAlertRequest: DeleteAlertRequest,
): string {
  return JSON.stringify(
    DeleteAlertRequest$outboundSchema.parse(deleteAlertRequest),
  );
}
