/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteOrganizationRequest = {
  orgId: string;
};

export type DeleteOrganizationResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type DeleteOrganizationRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const DeleteOrganizationRequest$outboundSchema: z.ZodMiniType<
  DeleteOrganizationRequest$Outbound,
  DeleteOrganizationRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function deleteOrganizationRequestToJSON(
  deleteOrganizationRequest: DeleteOrganizationRequest,
): string {
  return JSON.stringify(
    DeleteOrganizationRequest$outboundSchema.parse(deleteOrganizationRequest),
  );
}

/** @internal */
export const DeleteOrganizationResponse$inboundSchema: z.ZodMiniType<
  DeleteOrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  }),
);

export function deleteOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOrganizationResponse' from JSON`,
  );
}
