/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteWebhookSecurity = {
  bearerAuth: string;
};

export type DeleteWebhookRequest = {
  webhookId: string;
};

/** @internal */
export type DeleteWebhookSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const DeleteWebhookSecurity$outboundSchema: z.ZodMiniType<
  DeleteWebhookSecurity$Outbound,
  DeleteWebhookSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function deleteWebhookSecurityToJSON(
  deleteWebhookSecurity: DeleteWebhookSecurity,
): string {
  return JSON.stringify(
    DeleteWebhookSecurity$outboundSchema.parse(deleteWebhookSecurity),
  );
}

/** @internal */
export type DeleteWebhookRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const DeleteWebhookRequest$outboundSchema: z.ZodMiniType<
  DeleteWebhookRequest$Outbound,
  DeleteWebhookRequest
> = z.pipe(
  z.object({
    webhookId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookId: "webhook_id",
    });
  }),
);

export function deleteWebhookRequestToJSON(
  deleteWebhookRequest: DeleteWebhookRequest,
): string {
  return JSON.stringify(
    DeleteWebhookRequest$outboundSchema.parse(deleteWebhookRequest),
  );
}
