/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteModelRequest = {
  orgId: string;
  projectId: string;
  modelId: string;
};

/** @internal */
export type DeleteModelRequest$Outbound = {
  org_id: string;
  project_id: string;
  model_id: string;
};

/** @internal */
export const DeleteModelRequest$outboundSchema: z.ZodMiniType<
  DeleteModelRequest$Outbound,
  DeleteModelRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    modelId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      modelId: "model_id",
    });
  }),
);

export function deleteModelRequestToJSON(
  deleteModelRequest: DeleteModelRequest,
): string {
  return JSON.stringify(
    DeleteModelRequest$outboundSchema.parse(deleteModelRequest),
  );
}
