/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteProjectRequest = {
  orgId: string;
  projectId: string;
};

/** @internal */
export type DeleteProjectRequest$Outbound = {
  org_id: string;
  project_id: string;
};

/** @internal */
export const DeleteProjectRequest$outboundSchema: z.ZodMiniType<
  DeleteProjectRequest$Outbound,
  DeleteProjectRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
    });
  }),
);

export function deleteProjectRequestToJSON(
  deleteProjectRequest: DeleteProjectRequest,
): string {
  return JSON.stringify(
    DeleteProjectRequest$outboundSchema.parse(deleteProjectRequest),
  );
}
