/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetOperationRequest = {
  operationId: string;
};

export type GetOperationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AsyncOperation;
};

/** @internal */
export type GetOperationRequest$Outbound = {
  operation_id: string;
};

/** @internal */
export const GetOperationRequest$outboundSchema: z.ZodMiniType<
  GetOperationRequest$Outbound,
  GetOperationRequest
> = z.pipe(
  z.object({
    operationId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      operationId: "operation_id",
    });
  }),
);

export function getOperationRequestToJSON(
  getOperationRequest: GetOperationRequest,
): string {
  return JSON.stringify(
    GetOperationRequest$outboundSchema.parse(getOperationRequest),
  );
}

/** @internal */
export const GetOperationResponse$inboundSchema: z.ZodMiniType<
  GetOperationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.AsyncOperation$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getOperationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOperationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOperationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOperationResponse' from JSON`,
  );
}
