/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetModelRequest = {
  orgId: string;
  projectId: string;
  modelId: string;
};

export type GetModelResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ForecastModel;
};

/** @internal */
export type GetModelRequest$Outbound = {
  org_id: string;
  project_id: string;
  model_id: string;
};

/** @internal */
export const GetModelRequest$outboundSchema: z.ZodMiniType<
  GetModelRequest$Outbound,
  GetModelRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    modelId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      modelId: "model_id",
    });
  }),
);

export function getModelRequestToJSON(
  getModelRequest: GetModelRequest,
): string {
  return JSON.stringify(GetModelRequest$outboundSchema.parse(getModelRequest));
}

/** @internal */
export const GetModelResponse$inboundSchema: z.ZodMiniType<
  GetModelResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ForecastModel$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetModelResponse' from JSON`,
  );
}
