/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetAlertRequest = {
  orgId: string;
  projectId: string;
  alertId: string;
};

export type GetAlertResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Alert;
};

/** @internal */
export type GetAlertRequest$Outbound = {
  org_id: string;
  project_id: string;
  alert_id: string;
};

/** @internal */
export const GetAlertRequest$outboundSchema: z.ZodMiniType<
  GetAlertRequest$Outbound,
  GetAlertRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    alertId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      alertId: "alert_id",
    });
  }),
);

export function getAlertRequestToJSON(
  getAlertRequest: GetAlertRequest,
): string {
  return JSON.stringify(GetAlertRequest$outboundSchema.parse(getAlertRequest));
}

/** @internal */
export const GetAlertResponse$inboundSchema: z.ZodMiniType<
  GetAlertResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Alert$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getAlertResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAlertResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAlertResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAlertResponse' from JSON`,
  );
}
