/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetOrganizationRequest = {
  orgId: string;
};

export type GetOrganizationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Organization;
};

/** @internal */
export type GetOrganizationRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodMiniType<
  GetOrganizationRequest$Outbound,
  GetOrganizationRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}

/** @internal */
export const GetOrganizationResponse$inboundSchema: z.ZodMiniType<
  GetOrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Organization$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponse' from JSON`,
  );
}
