/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetWebhookSecurity = {
  bearerAuth: string;
};

export type GetWebhookRequest = {
  webhookId: string;
};

export type GetWebhookResponse = {
  headers: { [k: string]: Array<string> };
  result: models.WebhookEndpoint;
};

/** @internal */
export type GetWebhookSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const GetWebhookSecurity$outboundSchema: z.ZodMiniType<
  GetWebhookSecurity$Outbound,
  GetWebhookSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function getWebhookSecurityToJSON(
  getWebhookSecurity: GetWebhookSecurity,
): string {
  return JSON.stringify(
    GetWebhookSecurity$outboundSchema.parse(getWebhookSecurity),
  );
}

/** @internal */
export type GetWebhookRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const GetWebhookRequest$outboundSchema: z.ZodMiniType<
  GetWebhookRequest$Outbound,
  GetWebhookRequest
> = z.pipe(
  z.object({
    webhookId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookId: "webhook_id",
    });
  }),
);

export function getWebhookRequestToJSON(
  getWebhookRequest: GetWebhookRequest,
): string {
  return JSON.stringify(
    GetWebhookRequest$outboundSchema.parse(getWebhookRequest),
  );
}

/** @internal */
export const GetWebhookResponse$inboundSchema: z.ZodMiniType<
  GetWebhookResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.WebhookEndpoint$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookResponse' from JSON`,
  );
}
