/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetProjectRequest = {
  orgId: string;
  projectId: string;
};

export type GetProjectResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Project;
};

/** @internal */
export type GetProjectRequest$Outbound = {
  org_id: string;
  project_id: string;
};

/** @internal */
export const GetProjectRequest$outboundSchema: z.ZodMiniType<
  GetProjectRequest$Outbound,
  GetProjectRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
    });
  }),
);

export function getProjectRequestToJSON(
  getProjectRequest: GetProjectRequest,
): string {
  return JSON.stringify(
    GetProjectRequest$outboundSchema.parse(getProjectRequest),
  );
}

/** @internal */
export const GetProjectResponse$inboundSchema: z.ZodMiniType<
  GetProjectResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Project$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectResponse' from JSON`,
  );
}
