/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type InviteMemberRequest = {
  orgId: string;
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body: models.MemberInvite;
};

export type InviteMemberResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Member;
};

/** @internal */
export type InviteMemberRequest$Outbound = {
  org_id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.MemberInvite$Outbound;
};

/** @internal */
export const InviteMemberRequest$outboundSchema: z.ZodMiniType<
  InviteMemberRequest$Outbound,
  InviteMemberRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.MemberInvite$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function inviteMemberRequestToJSON(
  inviteMemberRequest: InviteMemberRequest,
): string {
  return JSON.stringify(
    InviteMemberRequest$outboundSchema.parse(inviteMemberRequest),
  );
}

/** @internal */
export const InviteMemberResponse$inboundSchema: z.ZodMiniType<
  InviteMemberResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Member$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function inviteMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<InviteMemberResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InviteMemberResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InviteMemberResponse' from JSON`,
  );
}
