/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListOrganizationsRequest = {
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of organizations
 */
export type ListOrganizationsResponseBody = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.Organization>;
};

export type ListOrganizationsResponse = {
  headers: { [k: string]: Array<string> };
  result: ListOrganizationsResponseBody;
};

/** @internal */
export type ListOrganizationsRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListOrganizationsRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationsRequest$Outbound,
  ListOrganizationsRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 20),
});

export function listOrganizationsRequestToJSON(
  listOrganizationsRequest: ListOrganizationsRequest,
): string {
  return JSON.stringify(
    ListOrganizationsRequest$outboundSchema.parse(listOrganizationsRequest),
  );
}

/** @internal */
export const ListOrganizationsResponseBody$inboundSchema: z.ZodMiniType<
  ListOrganizationsResponseBody,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.Organization$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listOrganizationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListOrganizationsResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListOrganizationsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listOrganizationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsResponse' from JSON`,
  );
}
