/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListWebhookDeliveriesSecurity = {
  bearerAuth: string;
};

export type ListWebhookDeliveriesRequest = {
  webhookId: string;
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of webhook deliveries
 */
export type ListWebhookDeliveriesResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.WebhookDelivery>;
};

/** @internal */
export type ListWebhookDeliveriesSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const ListWebhookDeliveriesSecurity$outboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesSecurity$Outbound,
  ListWebhookDeliveriesSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function listWebhookDeliveriesSecurityToJSON(
  listWebhookDeliveriesSecurity: ListWebhookDeliveriesSecurity,
): string {
  return JSON.stringify(
    ListWebhookDeliveriesSecurity$outboundSchema.parse(
      listWebhookDeliveriesSecurity,
    ),
  );
}

/** @internal */
export type ListWebhookDeliveriesRequest$Outbound = {
  webhook_id: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListWebhookDeliveriesRequest$outboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesRequest$Outbound,
  ListWebhookDeliveriesRequest
> = z.pipe(
  z.object({
    webhookId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 20),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookId: "webhook_id",
    });
  }),
);

export function listWebhookDeliveriesRequestToJSON(
  listWebhookDeliveriesRequest: ListWebhookDeliveriesRequest,
): string {
  return JSON.stringify(
    ListWebhookDeliveriesRequest$outboundSchema.parse(
      listWebhookDeliveriesRequest,
    ),
  );
}

/** @internal */
export const ListWebhookDeliveriesResponse$inboundSchema: z.ZodMiniType<
  ListWebhookDeliveriesResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.WebhookDelivery$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listWebhookDeliveriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhookDeliveriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhookDeliveriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhookDeliveriesResponse' from JSON`,
  );
}
