/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const ListModelsStatus = {
  Draft: "draft",
  Training: "training",
  Trained: "trained",
  Failed: "failed",
  Archived: "archived",
} as const;
export type ListModelsStatus = ClosedEnum<typeof ListModelsStatus>;

export type ListModelsRequest = {
  orgId: string;
  projectId: string;
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
  status?: ListModelsStatus | undefined;
};

/**
 * Paginated list of models
 */
export type ListModelsResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.ForecastModel>;
};

/** @internal */
export const ListModelsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListModelsStatus
> = z.enum(ListModelsStatus);

/** @internal */
export type ListModelsRequest$Outbound = {
  org_id: string;
  project_id: string;
  cursor?: string | undefined;
  limit: number;
  status?: string | undefined;
};

/** @internal */
export const ListModelsRequest$outboundSchema: z.ZodMiniType<
  ListModelsRequest$Outbound,
  ListModelsRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 20),
    status: z.optional(ListModelsStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
    });
  }),
);

export function listModelsRequestToJSON(
  listModelsRequest: ListModelsRequest,
): string {
  return JSON.stringify(
    ListModelsRequest$outboundSchema.parse(listModelsRequest),
  );
}

/** @internal */
export const ListModelsResponse$inboundSchema: z.ZodMiniType<
  ListModelsResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.ForecastModel$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsResponse' from JSON`,
  );
}
