/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListAlertsRequest = {
  orgId: string;
  projectId: string;
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of alerts
 */
export type ListAlertsResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.Alert>;
};

/** @internal */
export type ListAlertsRequest$Outbound = {
  org_id: string;
  project_id: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListAlertsRequest$outboundSchema: z.ZodMiniType<
  ListAlertsRequest$Outbound,
  ListAlertsRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 20),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
    });
  }),
);

export function listAlertsRequestToJSON(
  listAlertsRequest: ListAlertsRequest,
): string {
  return JSON.stringify(
    ListAlertsRequest$outboundSchema.parse(listAlertsRequest),
  );
}

/** @internal */
export const ListAlertsResponse$inboundSchema: z.ZodMiniType<
  ListAlertsResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.Alert$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listAlertsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAlertsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAlertsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAlertsResponse' from JSON`,
  );
}
