/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const Role = {
  Owner: "owner",
  Admin: "admin",
  Member: "member",
  Viewer: "viewer",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type ListMembersRequest = {
  orgId: string;
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
  role?: Role | undefined;
};

/**
 * Paginated list of members
 */
export type ListMembersResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.Member>;
};

/** @internal */
export const Role$outboundSchema: z.ZodMiniEnum<typeof Role> = z.enum(Role);

/** @internal */
export type ListMembersRequest$Outbound = {
  org_id: string;
  cursor?: string | undefined;
  limit: number;
  role?: string | undefined;
};

/** @internal */
export const ListMembersRequest$outboundSchema: z.ZodMiniType<
  ListMembersRequest$Outbound,
  ListMembersRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 20),
    role: z.optional(Role$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function listMembersRequestToJSON(
  listMembersRequest: ListMembersRequest,
): string {
  return JSON.stringify(
    ListMembersRequest$outboundSchema.parse(listMembersRequest),
  );
}

/** @internal */
export const ListMembersResponse$inboundSchema: z.ZodMiniType<
  ListMembersResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.Member$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMembersResponse' from JSON`,
  );
}
