/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListWebhooksSecurity = {
  bearerAuth: string;
};

export type ListWebhooksRequest = {
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of webhook endpoints
 */
export type ListWebhooksResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.WebhookEndpoint>;
};

/** @internal */
export type ListWebhooksSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const ListWebhooksSecurity$outboundSchema: z.ZodMiniType<
  ListWebhooksSecurity$Outbound,
  ListWebhooksSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function listWebhooksSecurityToJSON(
  listWebhooksSecurity: ListWebhooksSecurity,
): string {
  return JSON.stringify(
    ListWebhooksSecurity$outboundSchema.parse(listWebhooksSecurity),
  );
}

/** @internal */
export type ListWebhooksRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListWebhooksRequest$outboundSchema: z.ZodMiniType<
  ListWebhooksRequest$Outbound,
  ListWebhooksRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 20),
});

export function listWebhooksRequestToJSON(
  listWebhooksRequest: ListWebhooksRequest,
): string {
  return JSON.stringify(
    ListWebhooksRequest$outboundSchema.parse(listWebhooksRequest),
  );
}

/** @internal */
export const ListWebhooksResponse$inboundSchema: z.ZodMiniType<
  ListWebhooksResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.WebhookEndpoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhooksResponse' from JSON`,
  );
}
