/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListProjectsRequest = {
  orgId: string;
  /**
   * Opaque cursor for cursor-based pagination.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of projects
 */
export type ListProjectsResponse = {
  hasMore: boolean;
  nextCursor: string | null;
  data: Array<models.Project>;
};

/** @internal */
export type ListProjectsRequest$Outbound = {
  org_id: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const ListProjectsRequest$outboundSchema: z.ZodMiniType<
  ListProjectsRequest$Outbound,
  ListProjectsRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 20),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function listProjectsRequestToJSON(
  listProjectsRequest: ListProjectsRequest,
): string {
  return JSON.stringify(
    ListProjectsRequest$outboundSchema.parse(listProjectsRequest),
  );
}

/** @internal */
export const ListProjectsResponse$inboundSchema: z.ZodMiniType<
  ListProjectsResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    data: z.array(models.Project$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listProjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProjectsResponse' from JSON`,
  );
}
