/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListAlertHistoryRequest = {
  orgId: string;
  projectId: string;
  alertId: string;
  offset?: number | undefined;
  limit?: number | undefined;
  /**
   * Only return events triggered after this timestamp
   */
  since?: Date | undefined;
  /**
   * Only return events triggered before this timestamp
   */
  until?: Date | undefined;
};

/**
 * Paginated alert event history (offset-based)
 */
export type ListAlertHistoryResponse = {
  total: number;
  offset: number;
  limit: number;
  data: Array<models.AlertEvent>;
};

/** @internal */
export type ListAlertHistoryRequest$Outbound = {
  org_id: string;
  project_id: string;
  alert_id: string;
  offset: number;
  limit: number;
  since?: string | undefined;
  until?: string | undefined;
};

/** @internal */
export const ListAlertHistoryRequest$outboundSchema: z.ZodMiniType<
  ListAlertHistoryRequest$Outbound,
  ListAlertHistoryRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    alertId: z.string(),
    offset: z._default(z.int(), 0),
    limit: z._default(z.int(), 20),
    since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      alertId: "alert_id",
    });
  }),
);

export function listAlertHistoryRequestToJSON(
  listAlertHistoryRequest: ListAlertHistoryRequest,
): string {
  return JSON.stringify(
    ListAlertHistoryRequest$outboundSchema.parse(listAlertHistoryRequest),
  );
}

/** @internal */
export const ListAlertHistoryResponse$inboundSchema: z.ZodMiniType<
  ListAlertHistoryResponse,
  unknown
> = z.object({
  total: types.number(),
  offset: types.number(),
  limit: types.number(),
  data: z.array(models.AlertEvent$inboundSchema),
});

export function listAlertHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAlertHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAlertHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAlertHistoryResponse' from JSON`,
  );
}
