/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type TrainModelRequestBody = {
  hyperparameters?: models.Hyperparameters | undefined;
};

export type TrainModelRequest = {
  orgId: string;
  projectId: string;
  modelId: string;
  /**
   * Prevents duplicate operations when retrying requests.
   */
  idempotencyKey?: string | undefined;
  body?: TrainModelRequestBody | undefined;
};

export type TrainModelResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AsyncOperation;
};

/** @internal */
export type TrainModelRequestBody$Outbound = {
  hyperparameters?: models.Hyperparameters$Outbound | undefined;
};

/** @internal */
export const TrainModelRequestBody$outboundSchema: z.ZodMiniType<
  TrainModelRequestBody$Outbound,
  TrainModelRequestBody
> = z.object({
  hyperparameters: z.optional(models.Hyperparameters$outboundSchema),
});

export function trainModelRequestBodyToJSON(
  trainModelRequestBody: TrainModelRequestBody,
): string {
  return JSON.stringify(
    TrainModelRequestBody$outboundSchema.parse(trainModelRequestBody),
  );
}

/** @internal */
export type TrainModelRequest$Outbound = {
  org_id: string;
  project_id: string;
  model_id: string;
  "Idempotency-Key"?: string | undefined;
  body?: TrainModelRequestBody$Outbound | undefined;
};

/** @internal */
export const TrainModelRequest$outboundSchema: z.ZodMiniType<
  TrainModelRequest$Outbound,
  TrainModelRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    modelId: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: z.optional(z.lazy(() => TrainModelRequestBody$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      modelId: "model_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function trainModelRequestToJSON(
  trainModelRequest: TrainModelRequest,
): string {
  return JSON.stringify(
    TrainModelRequest$outboundSchema.parse(trainModelRequest),
  );
}

/** @internal */
export const TrainModelResponse$inboundSchema: z.ZodMiniType<
  TrainModelResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.AsyncOperation$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function trainModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<TrainModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrainModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrainModelResponse' from JSON`,
  );
}
