/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateAlertRequestBody = {
  name?: string | undefined;
  condition?: models.AlertCondition | undefined;
  channels?: Array<models.NotificationChannel> | undefined;
  enabled?: boolean | undefined;
};

export type UpdateAlertRequest = {
  orgId: string;
  projectId: string;
  alertId: string;
  body: UpdateAlertRequestBody;
};

/** @internal */
export type UpdateAlertRequestBody$Outbound = {
  name?: string | undefined;
  condition?: models.AlertCondition$Outbound | undefined;
  channels?: Array<models.NotificationChannel$Outbound> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const UpdateAlertRequestBody$outboundSchema: z.ZodMiniType<
  UpdateAlertRequestBody$Outbound,
  UpdateAlertRequestBody
> = z.object({
  name: z.optional(z.string()),
  condition: z.optional(models.AlertCondition$outboundSchema),
  channels: z.optional(z.array(models.NotificationChannel$outboundSchema)),
  enabled: z.optional(z.boolean()),
});

export function updateAlertRequestBodyToJSON(
  updateAlertRequestBody: UpdateAlertRequestBody,
): string {
  return JSON.stringify(
    UpdateAlertRequestBody$outboundSchema.parse(updateAlertRequestBody),
  );
}

/** @internal */
export type UpdateAlertRequest$Outbound = {
  org_id: string;
  project_id: string;
  alert_id: string;
  body: UpdateAlertRequestBody$Outbound;
};

/** @internal */
export const UpdateAlertRequest$outboundSchema: z.ZodMiniType<
  UpdateAlertRequest$Outbound,
  UpdateAlertRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    projectId: z.string(),
    alertId: z.string(),
    body: z.lazy(() => UpdateAlertRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      projectId: "project_id",
      alertId: "alert_id",
    });
  }),
);

export function updateAlertRequestToJSON(
  updateAlertRequest: UpdateAlertRequest,
): string {
  return JSON.stringify(
    UpdateAlertRequest$outboundSchema.parse(updateAlertRequest),
  );
}
