/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const Plan = {
  Free: "free",
  Pro: "pro",
  Enterprise: "enterprise",
} as const;
export type Plan = ClosedEnum<typeof Plan>;

export type UpdateOrganizationRequestBody = {
  name?: string | undefined;
  plan?: Plan | undefined;
  metadata?: { [k: string]: string } | null | undefined;
};

export type UpdateOrganizationRequest = {
  orgId: string;
  body: UpdateOrganizationRequestBody;
};

export type UpdateOrganizationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Organization;
};

/** @internal */
export const Plan$outboundSchema: z.ZodMiniEnum<typeof Plan> = z.enum(Plan);

/** @internal */
export type UpdateOrganizationRequestBody$Outbound = {
  name?: string | undefined;
  plan?: string | undefined;
  metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const UpdateOrganizationRequestBody$outboundSchema: z.ZodMiniType<
  UpdateOrganizationRequestBody$Outbound,
  UpdateOrganizationRequestBody
> = z.object({
  name: z.optional(z.string()),
  plan: z.optional(Plan$outboundSchema),
  metadata: z.optional(z.nullable(z.record(z.string(), z.string()))),
});

export function updateOrganizationRequestBodyToJSON(
  updateOrganizationRequestBody: UpdateOrganizationRequestBody,
): string {
  return JSON.stringify(
    UpdateOrganizationRequestBody$outboundSchema.parse(
      updateOrganizationRequestBody,
    ),
  );
}

/** @internal */
export type UpdateOrganizationRequest$Outbound = {
  org_id: string;
  body: UpdateOrganizationRequestBody$Outbound;
};

/** @internal */
export const UpdateOrganizationRequest$outboundSchema: z.ZodMiniType<
  UpdateOrganizationRequest$Outbound,
  UpdateOrganizationRequest
> = z.pipe(
  z.object({
    orgId: z.string(),
    body: z.lazy(() => UpdateOrganizationRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function updateOrganizationRequestToJSON(
  updateOrganizationRequest: UpdateOrganizationRequest,
): string {
  return JSON.stringify(
    UpdateOrganizationRequest$outboundSchema.parse(updateOrganizationRequest),
  );
}

/** @internal */
export const UpdateOrganizationResponse$inboundSchema: z.ZodMiniType<
  UpdateOrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.Organization$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateOrganizationResponse' from JSON`,
  );
}
