/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VerifyWebhookSignatureRequestBody = {
  /**
   * Raw JSON payload string
   */
  payload: string;
  /**
   * The X-Chronocast-Signature header value
   */
  signature: string;
  /**
   * The X-Chronocast-Timestamp header value
   */
  timestamp: Date;
};

export type VerifyWebhookSignatureRequest = {
  webhookId: string;
  body: VerifyWebhookSignatureRequestBody;
};

/**
 * Verification result
 */
export type VerifyWebhookSignatureResponse = {
  valid: boolean;
  reason?: string | null | undefined;
};

/** @internal */
export type VerifyWebhookSignatureRequestBody$Outbound = {
  payload: string;
  signature: string;
  timestamp: string;
};

/** @internal */
export const VerifyWebhookSignatureRequestBody$outboundSchema: z.ZodMiniType<
  VerifyWebhookSignatureRequestBody$Outbound,
  VerifyWebhookSignatureRequestBody
> = z.object({
  payload: z.string(),
  signature: z.string(),
  timestamp: z.pipe(z.date(), z.transform(v => v.toISOString())),
});

export function verifyWebhookSignatureRequestBodyToJSON(
  verifyWebhookSignatureRequestBody: VerifyWebhookSignatureRequestBody,
): string {
  return JSON.stringify(
    VerifyWebhookSignatureRequestBody$outboundSchema.parse(
      verifyWebhookSignatureRequestBody,
    ),
  );
}

/** @internal */
export type VerifyWebhookSignatureRequest$Outbound = {
  webhook_id: string;
  body: VerifyWebhookSignatureRequestBody$Outbound;
};

/** @internal */
export const VerifyWebhookSignatureRequest$outboundSchema: z.ZodMiniType<
  VerifyWebhookSignatureRequest$Outbound,
  VerifyWebhookSignatureRequest
> = z.pipe(
  z.object({
    webhookId: z.string(),
    body: z.lazy(() => VerifyWebhookSignatureRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookId: "webhook_id",
    });
  }),
);

export function verifyWebhookSignatureRequestToJSON(
  verifyWebhookSignatureRequest: VerifyWebhookSignatureRequest,
): string {
  return JSON.stringify(
    VerifyWebhookSignatureRequest$outboundSchema.parse(
      verifyWebhookSignatureRequest,
    ),
  );
}

/** @internal */
export const VerifyWebhookSignatureResponse$inboundSchema: z.ZodMiniType<
  VerifyWebhookSignatureResponse,
  unknown
> = z.object({
  valid: types.boolean(),
  reason: z.optional(z.nullable(types.string())),
});

export function verifyWebhookSignatureResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerifyWebhookSignatureResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyWebhookSignatureResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyWebhookSignatureResponse' from JSON`,
  );
}
