// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         cursor: "cursor",
 *         limit: 1,
 *         role: "owner"
 *     }
 */
export interface ListMembersRequest {
    /** Opaque cursor for cursor-based pagination. */
    cursor?: string;
    limit?: number;
    role?: Chronocast.ListMembersRequestRole;
}
