// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         email: "email"
 *     }
 */
export interface MemberInvite {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    email: string;
    role?: Chronocast.MemberInviteRole;
}
