// This file was auto-generated by Fern from our API Definition.

import { AlertsClient } from "./api/resources/alerts/client/Client.js";
import { DatasetsClient } from "./api/resources/datasets/client/Client.js";
import { MembersClient } from "./api/resources/members/client/Client.js";
import { ModelsClient } from "./api/resources/models/client/Client.js";
import { OperationsClient } from "./api/resources/operations/client/Client.js";
import { OrganizationsClient } from "./api/resources/organizations/client/Client.js";
import { PredictionsClient } from "./api/resources/predictions/client/Client.js";
import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace ChronocastClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ChronocastClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ChronocastClient.Options>;
    protected _organizations: OrganizationsClient | undefined;
    protected _members: MembersClient | undefined;
    protected _projects: ProjectsClient | undefined;
    protected _datasets: DatasetsClient | undefined;
    protected _models: ModelsClient | undefined;
    protected _predictions: PredictionsClient | undefined;
    protected _alerts: AlertsClient | undefined;
    protected _operations: OperationsClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: ChronocastClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get organizations(): OrganizationsClient {
        return (this._organizations ??= new OrganizationsClient(this._options));
    }

    public get members(): MembersClient {
        return (this._members ??= new MembersClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }

    public get datasets(): DatasetsClient {
        return (this._datasets ??= new DatasetsClient(this._options));
    }

    public get models(): ModelsClient {
        return (this._models ??= new ModelsClient(this._options));
    }

    public get predictions(): PredictionsClient {
        return (this._predictions ??= new PredictionsClient(this._options));
    }

    public get alerts(): AlertsClient {
        return (this._alerts ??= new AlertsClient(this._options));
    }

    public get operations(): OperationsClient {
        return (this._operations ??= new OperationsClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }
}
