// This file was auto-generated by Fern from our API Definition.

export const ChronocastEnvironment = {
    Production: "https://api.chronocast.dev/v1",
} as const;

export type ChronocastEnvironment = typeof ChronocastEnvironment.Production;
