// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "Idempotency-Key",
 *         name: "name",
 *         modelId: "model_id",
 *         condition: Chronocast.AlertCondition.threshold({
 *             metric: "metric",
 *             operator: "gt",
 *             value: 1.1,
 *             durationMinutes: 1
 *         }),
 *         channels: [Chronocast.NotificationChannel.email({
 *                 address: "address"
 *             })]
 *     }
 */
export interface AlertCreate {
    /** Prevents duplicate operations when retrying requests. */
    idempotencyKey?: string;
    name: string;
    modelId: string;
    condition: Chronocast.AlertCondition;
    channels: Chronocast.NotificationChannel[];
    enabled?: boolean;
}
