// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         offset: 1,
 *         limit: 1,
 *         since: new Date("2024-01-15T09:30:00.000Z"),
 *         until: new Date("2024-01-15T09:30:00.000Z")
 *     }
 */
export interface ListAlertHistoryRequest {
    offset?: number;
    limit?: number;
    /** Only return events triggered after this timestamp */
    since?: Date;
    /** Only return events triggered before this timestamp */
    until?: Date;
}
