// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateAlertRequest {
    name?: string;
    condition?: Chronocast.AlertCondition;
    channels?: Chronocast.NotificationChannel[];
    enabled?: boolean;
}
