// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const VerifyWebhookSignatureRequest: core.serialization.Schema<
    serializers.VerifyWebhookSignatureRequest.Raw,
    Chronocast.VerifyWebhookSignatureRequest
> = core.serialization.object({
    payload: core.serialization.string(),
    signature: core.serialization.string(),
    timestamp: core.serialization.date(),
});

export declare namespace VerifyWebhookSignatureRequest {
    export interface Raw {
        payload: string;
        signature: string;
        timestamp: string;
    }
}
