// This file was auto-generated by Fern from our API Definition.

import type * as Chronocast from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { WebhookEndpointCreateEventsItem } from "../../types/WebhookEndpointCreateEventsItem.js";

export const WebhookEndpointCreate: core.serialization.Schema<
    serializers.WebhookEndpointCreate.Raw,
    Omit<Chronocast.WebhookEndpointCreate, "idempotencyKey">
> = core.serialization.object({
    url: core.serialization.string(),
    events: core.serialization.list(WebhookEndpointCreateEventsItem),
});

export declare namespace WebhookEndpointCreate {
    export interface Raw {
        url: string;
        events: WebhookEndpointCreateEventsItem.Raw[];
    }
}
